### ISSUE TITLE
Background image can make Terminix and GNOME unresponding

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#352] opened 2016-05-27 21:17 UTC
Reproduce always

1. Set as background a heavy HD image
2. Set transparency 100%
3. Resize, move, open layouts in Terminix

Outcome:
It will respond slow, and eventually it will crash. I cant even jump to TTY and I need to hard restart PC. 

That behavior only happens with "heavy" background images. Could be a guard on image size? For example not bigger than 1MB? Or a warning? 

DUB version 0.9.24, built on Oct 27 2015
DMD64 D Compiler v2.071.0

System Fedora Rawhide
GTK 3.21.x

**Comment by gnunn1** [comment] 2016-05-27 21:40
What do you define as heavy, I tested with wallpaper sized issues (1920x1080) and didn't notice any issues. If github allows it, post your image and I'll have a look.

**Comment by gnunn1** [comment] 2016-05-27 22:49
Just a note to myself, this might be related to garbage collection.

**Comment by alex285** [comment] 2016-05-27 23:41
@gnunn1 an image can be HD and still "light", for example a single color jpg
Here is one of those I tested Terminix with:
http://imgur.com/SKCOdJl

**Comment by alex285** [comment] 2016-05-27 23:51
@gnunn1 imgur actually compresses the image. Thats the original size:
https://images6.alphacoders.com/371/371656.jpg

Also my bad. This ain't HD. This image is 8K really :/

**Comment by gnunn1** [comment] 2016-05-28 02:37
Thanks, I can reproduce with that image.

**Comment by gnunn1** [comment] 2016-05-28 03:39
I added a timer around the image generation to try to understand how a large image is affecting performance. Obviously for the center and tile layout modes performance is very good even for this 8k image, scale and stretch is pretty atrocious though with image generation taking 350-500 ms or so. 

Based on these observations, I've made some changes and it no longer crashes for me when using that image, though it's still slower then I'd like. The changes I made were:

* Apparently using setSourcePixbuf is quite slow, switched to caching an ImageSurface right from the get go
* Switched to using a format without alpha for ImageSurface
* Only support a 4K resolution maximum width and height, if the image is larger then that it caches a scaled down version globally

Unfortunately graphics and cairo is not my strongest area, I'm going to play some more tomorrow to see if it can be improved further. if I can't squeeze out better performance I may opt to lower the maximum size further.

**Comment by gnunn1** [comment] 2016-05-28 03:43
And I spoke too soon, just got it to crash after more playing around. I'll do more investigation tomorrow.

**Comment by gnunn1** [comment] 2016-05-28 04:01
One last thought, the other option would be to simply remove the scale and stretch options if it can't be made performant. I don't think gnome-terminal supported these options when it did have support for background images.

**Comment by egmontkob** [comment] 2016-05-28 08:11
Indeed terminix's memory consumption keeps growing on each repaint. As seen in the VIRT and RES fields in `top`, it grows significantly on each repaint (e.g. even while the cursor is blinking but the terminal is otherwise idle; it stops growing when the cursor goes steady).

This also happens with tiling background mode.

I guess it's a simple memory leak, maybe the actual rendered contents are kept in memory on each paint, or something like this.

An image of 9001x5626 pixels, even if converted to an in-memory 8-bit RGBA, would consume 200 MB. Okay, let's generously assume 400 MB beause maybe 16 bits are used for each channel, dunno. And once again about the same for the scaled version, and yet again once to construct the area to be painted. Not something that should cause the system to swap and became unusably slow.

As for the garbage collector: I've really no clue how it works in D/Gtk, but I'm just wondering whether it's possible to always reuse the existing Gtk objects (canvas? surface? whatever) for rendering the contents rather than throwing them away and allocating new ones on each paint.

**Comment by gnunn1** [comment] 2016-05-28 18:36
I went through the eye of gnome code (https://github.com/GNOME/eog/blob/8169e0ac6447ebeb1d1e809213ce82b814b62550/src/eog-scroll-view.c) to pick up some cairo tricks as I noticed that it was scaling the image from @alex285 image during resizing much quicker then terminix was.

The key is apparently setting the filter for the pattern, setting it to NEAREST results in a good compromise between performance and visual results. With this change the rendering time is down to 3-4 ms on my machine, a vast improvement over the 80-100 ms I was getting previously. 

As a result of this improvement, I switched over to directly rendering the image on the Context in draw instead of using a cached ImageSurface. If you test it and find the performance still isn't ideal, try changing the flag CACHE_RENDERED_BG_IMAGE in constants.d to true to re-enable the image cache and sees if it improves performance. However, since eog doesn't seem to do any fancy caching I'm hoping this won't be needed.

The tiling code in cairo.d is also vastly improved, didn't realize that cairo could handle this automatically by setting extend on the pattern to REPEAT.

Finally, I went through the code to ensure all of the temporary Context and Surface objects I create get destroyed, in my testing memory seems pretty stable when resizing.

Please try out these changes and let me know how things go. If rendering directly the context works well it will let me drop the additional caching code which will simplify things. Note that I'm still enforcing a maximum image size of 4K by scaling down images bigger then that to 4K, I tried the raw image as well and well things are closer to eog then before it still feels a bit sluggish. I think down-scaling to 4K should be acceptable personally.

**Comment by alex285** [comment] 2016-05-28 22:16
After that patch, the performance is hugely improved, and no crashes either, but it is still reducing the overall responsiveness of the Terminal. Perhaps adding some note there like "If you get performance issues, consider to turn background images of"? ..or "background images may reduce performance"?

When I set  `CACHE_RENDERED_BG_IMAGE = true` I get an error inside the if

```
  static if (CACHE_RENDERED_BG_IMAGE) {
            //Cached render
            ImageSurface isBGImage = null;
            AppWindow window = cast(AppWindow)getToplevel();
            if (window !is null) {
                isBGImage = window.getBackgroundImage(child);
            }
```

```
$ dub build --build=release --force
...
source/gx/terminix/session.d(895,13): Error: declaration gx.terminix.session.Session.onDraw.window is already defined
...
```

**Comment by alex285** [comment] 2016-05-28 22:22
Also, after that patch on Scale and Stretch the background can pixate.

**Comment by egmontkob** [comment] 2016-05-28 22:51
It's basically okay for me now. Definitely no sign of memleak, performance degradation over time, or bringing down the entire desktop. Thanks a lot! :)

I have a favorite test file (the output of a `ls -lR --color=always /`; ~40MB, ~650k lines) that I've been `time cat`'ing for quite some time now to measure vte's speed. Unfortunately there's a generic variation of the time required to cat it, e.g. it's normal for this to once take 7 seconds, and at the next attempt take 10 seconds because the kernel starts writing some data to disk, or who knows what... Also the time required seem to depend on the age of the vte widget (somehow it gets a little bit slower if the given vte has already processed many lines, probably it can be justified by the underlying way of storing the scrollback in a file), depends on the size of the terminal, of course on the tabs I have open in my browser :) and a whole lot more. So I usually repeat this multiple times and have a "feeling" about the required time, rather than a precise measurement.

Given this test file, and a few measurements with a new vte all the time, cat'ing without background (with transparency) takes 7-8 seconds, with tiled/centered background it takes 8-9 seconds, and with scaled/stretched background it's 10-11 seconds.

I personally wouldn't mind this at most 1.5x slowdown at all, I think it's totally okay to say that a background image has this performance penalty. What I don't understand at all is why different resize methods result in different timing. I mean, all four modes perform a one-time scaling to an uncompressed pixmap matching the window's size, and from then onwards they should do the same. What am I missing?

**Comment by gnunn1** [comment] 2016-05-29 00:40
@egmontkob The things is that they no longer do a one-time rendering of the image since as I mentioned earlier I turned off the code that did that considering how much things improved. You can turn it back on by setting ```CACHE_RENDERED_BG_IMAGE = true``` in constants.d and re-compile. I'd be interested in seeing how your tests perform with the two different scenarios. As I'd mentioned, I'd prefer to remove this caching code to simplify things if I could, considering the nature of your test I'm not too worried about the 1.5 hit, I think for most real-world scenarios it wouldn't be noticeable.

@alex285 You can play around with the algorithm used to interpolate the scaling and see the different results in terms of quality and performance, it's at lines 143 and 163 in cairo.d for the SCALE and STRETCH options respectively. You'll see a line like this:

```
cr.getSource().setFilter(cairo_filter_t.NEAREST)
```

The other ones available include: ```FAST, GOOD, BEST, NEAREST, BILINEAR```

Reviewing the comments in the GTK, I think I mis-read about NEAREST, I'm going to play with this some more and see which algorithm is the best.

**Comment by gnunn1** [comment] 2016-05-29 00:55
@alex285 I checked in a fix for the issue you had with ```CACHE_RENDERED_BG_IMAGE = true```

**Comment by egmontkob** [comment] 2016-05-29 05:54
Sorry, it was too late last night, I didn't read your message carefully. Also it didn't occur to me you could've disabled caching, and didn't realize this brought back all the previous problems.

Please do not disable it. That's just a bad design for all the reasons outlined in #340 plus down below (as opposed to the current bug which is perhaps just a small implementation mistake of the correct design).

Scaling the image is an expensive operation. The 1.5x slowdown is the result of always re-scaling _and_ vte realizing that painting is slow and hence repainting way less often. So scaling is really not as cheap as it looks. You can see when cat'ing a large file that the screen is updated in a much lower FPS rate. Also if you press Enter at the shell prompt in the bottom row, there's a noticeable delay before the entire contents scroll up.

It'd be interesting to record a text editor session (which is a more typical use of a terminal than cat'ing giant files) with timing and replay it (using `script(replay) -t`), and measure the CPU time burnt by Terminix itself. This time, as opposed to the "cat a large file" test, I'm pretty sure the CPU consumption would increase by magnitudes. For each tiny repaint of a part of the screen an entire giant jpg has to be scaled down. This would consume much more power, drain the battery way sooner etc.

I'll play with re-enabling caching in the current codebase when I'll have time (not right now).

**Comment by gnunn1** [comment] 2016-05-29 14:08
@egmontkob I've turned the image caching back on, fixed a memory associated with it and changed the cairo scaling filter to GOOD from NEAREST. Hopefully this addresses everything and I can close this off. If you and @alex285 could test one more time I'd appreciate it.

**Comment by gnunn1** [comment] 2016-05-29 17:33
After testing on my Macbook, I switched to BILINEAR from GOOD. On my gaming laptop there wasn't much difference between the two but on the Macbook BILINEAR is around 3ms whereas GOOD is 30-40ms.

I'm thinking I might need to make this a hidden option in gsettings that could be tweaked via dconf if needed.

**Comment by gnunn1** [comment] 2016-05-29 18:14
Screw it, hidden option added for the scale algorithm.

**Comment by egmontkob** [comment] 2016-05-29 20:09
Looks good to me now, thanks! Fast and doesn't eat memory.

Given that the image is only scaled once per initialization and per resize, I'm not too much concerned about the algorithm, or about making it configurable. I'd probably choose one that produces good quality, or is somewhere halfway, but not on the "fast but crappy" end of the scale.

**Comment by gnunn1** [comment] 2016-05-29 20:11
@egmontkob Thanks for your and @alex285 help testing this, I'm going to close this issue now.

I did end up making the algorithm changeable in dconf, based on the different performance of my macbook (which uses an AMD GPU) I figured it's best to leave an out for people.

**Closed by gnunn1** 2016-05-29 20:11 UTC
Labels: bug
