### ISSUE TITLE
w3m-img can't display image

### ISSUE THREAD

**Issue by AnDroidEL** [gnunn1/terminix#540] opened 2016-10-23 16:51 UTC
I've tested it in other terminals as XTerm and Gnome-terminal, and simply it works. Only in my Terminix terminal doesn't.

You can check the discussion in this issue: [https://github.com/dylanaraps/neofetch/issues/392](https://github.com/dylanaraps/neofetch/issues/392).

What could it be?

---

I'm using Terminix 1.3.0 (stable version) and the OS is Arch Linux.

**Comment by gnunn1** [comment] 2016-10-23 17:11
Do you have the same issues in gnome-terminal?

Also, I don't use this program, if you want me to look at it your going to have to spell out how to reproduce the issue.

**Comment by AnDroidEL** [comment] 2016-10-23 18:55
> Do you have the same issues in gnome-terminal?

No, I don't. Gnome-terminal works well.

> Also, I don't use this program, if you want me to look at it your going to have to spell out how to reproduce the issue.

The first thing was running directly the command `neofetch` in Terminix. I had configured the configs file of neofetch before, just setting the image path and size. The result is no image appeared.

The second thing was running the Terminix indirectly as a process from other terminal, as XTerm and also Gnome-terminal, by the command `terminix --profile none --new-process`. The result is a blank block space in the Terminix, but the image is shown in the terminal where I ran the command previously.

That is equals to what @dylanaraps has told:

> I can reproduce this on my system using the following steps:
> 
> 1. Open a terminal emulator that isn't terminix.
> 2. Launch terminix from this new terminal emulator.
> 3. Launch neofetch from the new terminix window.
> 4. The image will render in the 1st terminal and not terminix.

Still according with @dylanaraps:

> To me this seems to be a bug between w3m-img and terminix [...]

That is, neofetch depends of w3m-img (w3m) to render the image in the terminal, and is probably a bug between them. Does exist a way to solve that? What you need I can help somehow.

**Comment by gnunn1** [comment] 2016-10-23 18:59
I just need to know what do I need to do to replicate this in terms of step by step instructions, I'm not really too interested in learning how neofetch works.

Also, terminix uses DBus activation, you could try turning this off in the desktop file by setting DBusActivatable to false (note you need to restart gnome-shell after changing this)

**Comment by egmontkob** [comment] 2016-10-23 19:09
IMO this whole concept of how w3m-img works is inherently brain-damaged :)

It relies on $WINDOWID (and I guess this is what's missing from Terminix) to figure out the location of the window (so it depends on X, there goes Wayland/Mir) and draws there.

The header/tab bar of gnome-terminal probably breaks the way the location is calculated. Becomes broken as soon as you drag-n-drop a gnome-terminal tab between two windows (since $WINDOWID cannot be updated so it still refers to the old window, another reason why it's broken by design and probably gnome-terminal shouldn't set this variable either).

Hopeless to position the picture at the right place with Terminix's paned layout.

**Comment by AnDroidEL** [comment] 2016-10-23 19:32
> I just need to know what do I need to do to replicate this in terms of step by step instructions, I'm not really too interested in learning how neofetch works.

OK. I'm sorry. Just:

1. Install `neofetch` through the AUR.
2. Run `neofetch --image wall` and check if shows the image of your current desktop wallpaper.

> Also, terminix uses DBus activation, you could try turning this off in the desktop file by setting DBusActivatable to false (note you need to restart gnome-shell after changing this)

Nothing happen.

**Comment by gnunn1** [comment] 2016-10-23 19:32
Thanks @egmontkob for the input, that's really helpful. I'll add the WINDOWID environment variable. If fixing this takes more then that then I'll probably punt on it.

**Comment by gnunn1** [comment] 2016-10-23 19:58
So I'm having a quick look at this, I'm not sure how fixable this is as there is a bit of a chken and egg going on here. When I spawn the terminal and set the environment variables, the VTE window hasn't been realized yet so the XID isn't available. I'll have to think about this some more.

**Comment by gnunn1** [comment] 2016-10-23 23:48
I've attempted to do this, but I'm stuck on getting the XID for the first terminal. As per my previous comment, since nothing is realized at this point no GdkWindow has been created. I've tried a few different things with no success.

However, when splitting a terminal I could get that XID at that point, however neofetch still doesn't work. I may end up closing this as ```won't fix``` as I'm not particularly interested in spending a lot of time on this.

Finally, I made one other change which is to remove the WINDOWID if inherited by the process, this will fix the issue of the wallpaper appearing in gnome-terminal when launching terminix.

**Comment by dylanaraps** [comment] 2016-10-23 23:53
This isn't necessarily a neofetch issue, it affects any program that uses `w3m-img` to display images in the terminal. (`w3m`, `ranger` and etc) 

It might be worth changing the title to reflect this.

**Comment by egmontkob** [comment] 2016-10-24 07:03
> I'm stuck on getting the XID for the first terminal

You could take a look at gnome-terminal. I have no clue how it does this. My wild guess (not knowing much about X programming) is create toplevel window (unmapped) -> get WINDOWID -> add vte -> map the whole thing.

> I'm not particularly interested in spending a lot of time on this

I can totally understand you :)

**Comment by gnunn1** [comment] 2016-10-24 08:36
I figured out the issue with the xid, I need to explicitly call window.realize(). I also need to refactor the session object to split creation and initialisation so the session can be added to the widget hierarchy before the terminal is initialised.

**Comment by gnunn1** [comment] 2016-10-24 23:05
So I've added the WINDOWID environment variable to terminix setting it to the XID of the top level window, however w3m-img still doesn't work so I'm kind of stumped at this point.

**Comment by gnunn1** [comment] 2016-10-25 00:04
I think the WINDOWID needs to the parent window (i.e. the Terminal EventBox) rather then the top level window. However, doing this leads to some visual artifacts and the image is only drawn momentarily before disappearing again.

At this point I've burned enough time on this and I'm closing it as a Won't Fix.

**Closed by gnunn1** 2016-10-25 00:04 UTC
Labels: bug, Low Priority, wontfix
