### ISSUE TITLE
New terminal open in / dir directory and not ~/

### ISSUE THREAD

**Issue by dbasinge** [gnunn1/terminix#216] opened 2016-04-07 17:11 UTC
in terminix 0.56, my new terminal windows are opening in the / directory and not in my home directory any more. Is that a bug or is there a way to change this behaviour.

**Comment by gnunn1** [comment] 2016-04-07 17:29
Duplicate of #214, fixed in git.

**Closed by gnunn1** 2016-04-07 17:29 UTC
