### ISSUE TITLE
Custom command trap

### ISSUE THREAD

**Issue by Uzytkownik2** [gnunn1/terminix#386] opened 2016-07-09 19:09 UTC
When someone set up "Run a custom command instead of my shell" with option exiting terminal after this, then is situation where Terminix is no longer able to work even after reinstall.

**Comment by gnunn1** [comment] 2016-07-09 19:12
I can't reproduce with master, which version are you using? Also, what command are you running?

**Comment by Uzytkownik2** [comment] 2016-07-09 19:13
Stable 1.0.0 on Ubuntu 16. Just echo "something".

**Comment by Uzytkownik2** [comment] 2016-07-09 20:02
If there is any file where Terminix stores settings such as custom commands?  I can't find ~/.config/terminix file.

**Comment by gnunn1** [comment] 2016-07-09 20:19
Terminix stores all of the settings in dconf under the key com.gexperts.Terminix

Since I can't reproduce it on master and I'll be pushing out a new version in a week it will hopefully be fixed then.

**Comment by gnunn1** [comment] 2016-07-13 23:11
@Uzytkownik2 I just pushed out a beta release, can you try it and see if it fixes this issue for you.

**Comment by Uzytkownik2** [comment] 2016-07-17 13:25
@gnunn1 after installation new beta release it is the same situation. It is not sure whether we mean the same thing so I took a photo: 

![terminix](https://cloud.githubusercontent.com/assets/20256895/16900871/211073e0-4c32-11e6-8a06-95af968862c6.png)

After new reopening Terminix, terminal is no longer able to work. Re-install nothing change, I can only fix it through Dconf Editor.

**Comment by gnunn1** [comment] 2016-07-17 14:30
Is that your default profile, if so then this is the expected behavior when you are using those settings. Essentially, terminix runs your custom command and since the command doesn't block, exists right away.

If this is a case where you want the command to just run in specific circumstances, add it a new non-default profile and then when running terminix select that profile using the --profile switch.

**Comment by gnunn1** [comment] 2016-07-19 13:17
@Uzytkownik2 Are you OK with my previous answer so I can close this or am I misunderstanding?

**Comment by Uzytkownik2** [comment] 2016-07-19 17:42
@gnunn1 you say that is expected behaviour so you can close this issue.

**Comment by gnunn1** [comment] 2016-07-19 20:41
Thanks!

**Closed by gnunn1** 2016-07-19 20:41 UTC
Labels: bug, Can't Reproduce
