### ISSUE TITLE
Disable Shortcuts Temporarily

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#223] opened 2016-04-10 12:18 UTC
I'm actually gonna leave four bugs here. 
I changed "View Sidebar" shortcut to previous key binding (Ctrl+S) that is now used on "Save" 

1. It didn't warn me that the shortcut was already in use
2. The shortcut (Ctrl+S) is still set on Save, even if it isn't working anymore
3. The changes applied after I had to restart Terminix and not instantly (a notification maybe?)
4. The Overlay Help hasn't updated the new keybindings

**Comment by alex285** [comment] 2016-04-10 12:20
Also, I don't think that F12 is a good default keybinding for sidebar. It is a very useful shortcut, but hard to use on F12.

**Comment by gnunn1** [comment] 2016-04-10 16:07
@alex285 I'm open to suggestions for default shortcuts, see #187 for some discussion about it.

**Comment by gnunn1** [comment] 2016-04-12 02:37
@alex285 I have added some new code that checks if a shortcut is assigned elsewhere and gives you the option to disable the other shortcut and assign it to the action or do nothing. That should take care of 1 and 2, however I could not reproduce 3 and 4 after the fix. Please test and re-open this issue if you are still having issues.

**Comment by alex285** [comment] 2016-04-12 07:12
@gnunn1 Awesome! You fixed all 4! So two more!

1. On S/C Overlay Help, when you search the shortcuts are invisible
2. A way to just disable a shortcut?

Basically on second you need to relayout the whole shortcut section (thus the preferences window) to provide an option to disable a shortcut but without losing its keybind, so I open another issue with it. Another smaller issue is that Terminix lets you add S/C like "Enter" which is basically wrong.

**Comment by gnunn1** [comment] 2016-04-12 16:40
1. Looks like a bug with Terminix but not sure what I'm doing wrong, I'll have to investigate

2. Are you just looking for the checkbox ike gnome terminal has that allows you to disable all shortcuts?

In terms of preventing shortcuts like the Enter key, no plans to do that because with all the different types of keyboards out there plus accessibility requirements (i.e. someone with Parkinson's re-mapping keys in a weird way to compensate for shaking) I think this is just more trouble then it's worth.

**Comment by gnunn1** [comment] 2016-04-13 02:02
Looks like 1 is a bug with GTK, opened a bug report here:

https://bugzilla.gnome.org/show_bug.cgi?id=764975

**Comment by alex285** [comment] 2016-04-13 09:31
> Are you just looking for the checkbox ike gnome terminal has that allows you to disable all shortcuts?

No. I'm looking for disabling keys separately but without losing their values. Like a simple checkbox/switch or a link (enable/disable) next to a key. It is a common concept in games for easily re-programming your shortcuts, where you can also get alternative keybindings. Something that KDE also does for example. 

The benefit is that when you re-programming your keys, and you want to change them, you shouldn't go one by one and set the values back. It is something that makes people not bothered changing S/C in casual apps, when they do change S/C in games, because there is more sophisticated design there.

Another example is what dconf-editor 320 does with keys. You can restore a default key, but without lose your custom value. Even if the design there is a bit weird.

**Comment by woybi** [comment] 2016-07-12 17:26
And what about fully disabling shortcuts? On gnome-terminal there is a check box to fully disable all shortcut (it still keeps the values, it just makes it useless until you uncheck the box). I can't use Terminix with all those shortcuts that gets on my way; i'm waiting for it to be disableable.

**Comment by gnunn1** [comment] 2016-07-13 22:49
I've added the ability to disable the shortcuts globally, I don't think I'm going to take this any further at this point hence closing the issue.

**Closed** 2016-07-13 22:49 UTC
Labels: enhancement
