### ISSUE TITLE
Session title not displayed properly

### ISSUE THREAD

**Issue by michael-rapp** [gnunn1/terminix#779] opened 2017-02-17 21:40 UTC
I have noticed a minor UI glitch in Terminix. It is only a small issue, but somehow it bothers me anyway. Frequently, immediately after I started Terminix, the title of the default session is not displayed properly. Instead, the text is cut off (see attached screenshot). When the window is moved, the UI seems to be updated and the issue disappears. Most of the time I start Terminix using a shortcut (Ctrl + Alt + T), which I configured in the "Keyboard" panel of the Gnome settings. It seems like this issue does not appear when starting terminix from the app launcher.

My system:
Arch Linux
Gnome 3.22.2
GTK3 3.22.8
Terminix 1.4.2

Edit: This has nothing to do with the custom theme, which can be seen in the screenshot. It also happens when using the default Adwaita theme.

![screenshot from 2017-02-17 22-29-39](https://cloud.githubusercontent.com/assets/6638695/23084177/5d56de24-f561-11e6-9288-6c0290faed59.png)

**Comment by gnunn1** [comment] 2017-02-17 22:03
Might be related to #551

**Comment by michael-rapp** [comment] 2017-02-17 22:19
Yes, I think this is the same issue.

**Comment by gnunn1** [comment] 2017-02-17 22:40
I'm not able to reproduce on master, can you try the ```terminix-git``` package in AUR and see if you can still reproduce it.

**Comment by michael-rapp** [comment] 2017-02-17 22:55
After installing the `terminix-git` package I am not able to reproduce it either.

**Comment by michael-rapp** [comment] 2017-02-17 22:57
I have to correct myself...it just occured again.

**Comment by gnunn1** [comment] 2017-02-17 23:18
I've checked in a change to try to workaround it, can you re-install ```terminix-git``` and see if it makes any difference.

**Comment by michael-rapp** [comment] 2017-02-17 23:42
I re-installed and tried again. It still occurred 2 or 3 times, but I started hundreds of instances and in most cases everything looked fine. So this is definitively an improvement considering the fact, that the issue occurred most of the time before.

**Comment by gnunn1** [comment] 2017-02-17 23:52
OK thanks, glad it is helping. I'll see what other options could be applied.

**Comment by gnunn1** [comment] 2017-02-18 01:10
I've made one more change, can you try this as well please.

**Comment by michael-rapp** [comment] 2017-02-18 01:22
It still occurs in rare cases.

**Comment by gnunn1** [comment] 2017-02-18 01:28
I've made one more change, can you try this one out again please. Sorry to put you through this, but when I can't duplicate it's difficult.

**Comment by michael-rapp** [comment] 2017-02-18 01:34
I am sorry, but I still encounter it sometimes.

**Comment by gnunn1** [comment] 2017-02-18 02:20
Thanks, I've got one last attempt I've checked in, if that doesn't work I'm out of ideas for now. Please give it a try and let me know, thanks for your patience.

**Comment by michael-rapp** [comment] 2017-02-18 13:44
Your last change doesn't seem to change anything. However, this is only a very small issue and it only occurs rarely after your patches.

**Closed** 2017-02-18 18:32 UTC
Labels: bug
