### ISSUE TITLE
Ctrl-O issue

### ISSUE THREAD

**Issue by leoheck** [gnunn1/terminix#438] opened 2016-08-09 13:07 UTC
The default ``Ctrl-o`` shortcut is wrong, it suppresses ``Ctrl-o`` expected by other applications like ``nano``. It should not be used by default. Please, use something different like ``Ctrl-Shift-o``

**Comment by gnunn1** [comment] 2016-08-09 13:10
Duplicate of #330

**Closed by gnunn1** 2016-08-09 13:10 UTC
