### ISSUE TITLE
Terminix crashs when changing profile settings 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [gnunn1/terminix#17] opened 2016-01-13 22:42 UTC
```
***MEMORY-ERROR***: terminix[19395]: GSlice: assertion failed: sinfo->n_allocated > 0
Aborted (core dumped)
```

**Comment by gnunn1** [comment] 2016-01-13 22:54
Thanks for the report, based on your other report I assume you are using Fedora? What version are you using?

**Comment by bil-elmoussaoui** [comment] 2016-01-13 23:00
I'm using Fedora 23 with Gnome 3.18.3

**Comment by gnunn1** [comment] 2016-01-14 00:08
Is this reproducible and was there a specific setting you were changing? If it's reproducible, does it run better if you run it as follows:

G_SLICE=always-malloc terminix

I'm not having any luck with reproducing it in my Fedora VM, though I did discover a couple of other issues.

**Comment by bil-elmoussaoui** [comment] 2016-01-14 00:14
Yes i still can reproduce it, all i have is to play with profiles settings 
```

(terminix:22665): Gtk-CRITICAL **: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed

(terminix:22665): Gtk-CRITICAL **: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed

(terminix:22665): GLib-CRITICAL **: g_variant_get_int64: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT64)' failed
*** Error in `terminix': free(): invalid pointer: 0x00007f31901a40c0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x77da5)[0x7f318f41bda5]
/lib64/libc.so.6(+0x804fa)[0x7f318f4244fa]
/lib64/libc.so.6(cfree+0x4c)[0x7f318f427cac]
/lib64/libglib-2.0.so.0(g_free+0xe)[0x7f3189dc15ee]
/lib64/libglib-2.0.so.0(g_slice_free1+0x7d)[0x7f3189dd8d9d]
terminix(_D3gdk4RGBA4RGBA6__dtorMFZv+0x34)[0x7dce34]
======= Memory map: ========
00400000-00a94000 r-xp 00000000 fd:02 4071921                            /usr/bin/terminix
00c94000-00d55000 rw-p 00694000 fd:02 4071921                            /usr/bin/terminix
00d55000-00d69000 rw-p 00000000 00:00 0 
019d4000-02a68000 rw-p 00000000 00:00 0                                  [heap]
7f316b339000-7f316b38d000 r--p 00000000 fd:02 5113198                    /usr/share/fonts/dejavu/DejaVuSansMono.ttf
7f316b38d000-7f316b3e2000 r--p 00000000 fd:02 5113204                    /usr/share/fonts/dejavu/DejaVuSerifCondensed-BoldItalic.ttf
7f316b3e2000-7f316b42f000 r--p 00000000 fd:00 274125                     /home/bilal/.local/share/fonts/DejaVu Sans Mono Bold for Powerline.ttf
7f316b444000-7f316b499000 r--p 00000000 fd:02 5113206                    /usr/share/fonts/dejavu/DejaVuSerifCondensed.ttf
7f316b499000-7f316b4eb000 r--p 00000000 fd:00 274126                     /home/bilal/.local/share/fonts/DejaVu Sans Mono for Powerline.ttf
7f316b4eb000-7f316b540000 r--p 00000000 fd:02 5113200                    /usr/share/fonts/dejavu/DejaVuSerif-BoldItalic.ttf
7f316b540000-7f316b595000 r--p 00000000 fd:02 5113205                    /usr/share/fonts/dejavu/DejaVuSerifCondensed-Italic.ttf
7f316b595000-7f316b5e6000 r--p 00000000 fd:02 5113203                    /usr/share/fonts/dejavu/DejaVuSerifCondensed-Bold.ttf
7f316b622000-7f316b780000 r-xp 00000000 fd:02 4071100                    /usr/lib64/libxml2.so.2.9.3
7f316b780000-7f316b980000 ---p 0015e000 fd:02 4071100                    /usr/lib64/libxml2.so.2.9.3
7f316b980000-7f316b988000 r--p 0015e000 fd:02 4071100                    /usr/lib64/libxml2.so.2.9.3
7f316b988000-7f316b98a000 rw-p 00166000 fd:02 4071100                    /usr/lib64/libxml2.so.2.9.3
7f316b98a000-7f316b98b000 rw-p 00000000 00:00 0 
7f316b98b000-7f316b9c2000 r-xp 00000000 fd:02 4071464                    /usr/lib64/libcroco-0.6.so.3.0.1
7f316b9c2000-7f316bbc2000 ---p 00037000 fd:02 4071464                    /usr/lib64/libcroco-0.6.so.3.0.1
7f316bbc2000-7f316bbc5000 r--p 00037000 fd:02 4071464                    /usr/lib64/libcroco-0.6.so.3.0.1
7f316bbc5000-7f316bbc6000 rw-p 0003a000 fd:02 4071464                    /usr/lib64/libcroco-0.6.so.3.0.1
7f316bbc6000-7f316bbfb000 r-xp 00000000 fd:02 4073221                    /usr/lib64/librsvg-2.so.2.40.13
7f316bbfb000-7f316bdfb000 ---p 00035000 fd:02 4073221                    /usr/lib64/librsvg-2.so.2.40.13
7f316bdfb000-7f316bdfc000 r--p 00035000 fd:02 4073221                    /usr/lib64/librsvg-2.so.2.40.13
7f316bdfc000-7f316bdfd000 rw-p 00036000 fd:02 4073221                    /usr/lib64/librsvg-2.so.2.40.13
7f316bdfd000-7f316bdff000 r-xp 00000000 fd:02 4456742                    /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7f316bdff000-7f316bffe000 ---p 00002000 fd:02 4456742                    /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7f316bffe000-7f316bfff000 r--p 00001000 fd:02 4456742                    /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7f316bfff000-7f316c000000 rw-p 00002000 fd:02 4456742                    /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7f316c000000-7f316c022000 rw-p 00000000 00:00 0 
7f316c022000-7f3170000000 ---p 00000000 00:00 0 
7f3170000000-7f3170022000 rw-p 00000000 00:00 0 
7f3170022000-7f3174000000 ---p 00000000 00:00 0 
7f3174000000-7f3174021000 rw-p 00000000 00:00 0 
7f3174021000-7f3178000000 ---p 00000000 00:00 0 
7f3178007000-7f3178043000 r--p 00000000 fd:00 274123                     /home/bilal/.local/share/fonts/DejaVu Sans Mono Oblique for Powerline.ttf
7f3178043000-7f31780c3000 rw-s 00000000 00:05 16154644                   /SYSV00000000 (deleted)
7f31780c3000-7f31780dc000 r--p 00000000 fd:02 5124990                    /usr/share/icons/Adwaita/icon-theme.cache
7f31780dc000-7f3178162000 r--p 00000000 fd:02 4858953                    /usr/share/icons/Numix/icon-theme.cache
7f3178162000-7f3178191000 r--p 00000000 fd:02 5260646                    /usr/share/icons/Numix-Circle/icon-theme.cache
7f3178191000-7f317819c000 r-xp 00000000 fd:02 4070712                    /usr/lib64/libnss_files-2.22.so
7f317819c000-7f317839b000 ---p 0000b000 fd:02 4070712                    /usr/lib64/libnss_files-2.22.so
7f317839b000-7f317839c000 r--p 0000a000 fd:02 4070712                    /usr/lib64/libnss_files-2.22.so
7f317839c000-7f317839d000 rw-p 0000b000 fd:02 4070712                    /usr/lib64/libnss_files-2.22.so
7f317839d000-7f31783a3000 rw-p 00000000 00:00 0 
7f31783bb000-7f31783c3000 r--p 00000000 fd:02 5139459                    /usr/share/icons/hicolor/icon-theme.cache
7f31783c3000-7f31783cc000 r--p 00000000 fd:02 5134249                    /usr/share/icons/gnome/icon-theme.cache
7f31783dc000-7f31783e6000 r--p 00000000 fd:00 275862                     /home/bilal/.config/dconf/user
7f3178410000-7f3178420000 rw-p 00000000 00:00 0 
7f3178420000-7f317842b000 r--p 00000000 fd:02 4737755                    /usr/share/fonts/myfonts/ufonts.com_futura-bk-bt-book.ttf
7f317842b000-7f317842d000 r--s 00000000 fd:02 6686919                    /var/cache/fontconfig/87f5e051180a7a75f16eb6fe7dbd3749-le64.cache-7
7f317842d000-7f3178438000 r--s 00000000 fd:02 6685036                    /var/cache/fontconfig/b79f3aaa7d385a141ab53ec885cc22a8-le64.cache-7
7f3178438000-7f317843a000 r--s 00000000 fd:02 6686959                    /var/cache/fontconfig/2e1514a9fdd499050989183bb65136db-le64.cache-7
7f317843a000-7f317843b000 r--s 00000000 fd:02 6686848                    /var/cache/fontconfig/7ef2298fde41cc6eeb7af42e48b7d293-le64.cache-7
7f317843b000-7f317843d000 r--s 00000000 fd:02 6686958                    /var/cache/fontconfig/3f821257dd33660ba7bbb45c32deb84c-le64.cache-7
7f317843d000-7f317843e000 r--s 00000000 fd:02 6686957                    /var/cache/fontconfig/4e602040080c966cb821813a3e584564-le64.cache-7
7f317843e000-7f3178441000 r--s 00000000 fd:02 6687345                    /var/cache/fontconfig/830f035fa84a65ce80e050178dbb630d-le64.cache-7
7f3178441000-7f3178442000 r--s 00000000 fd:02 6686955                    /var/cache/fontconfig/81a173283b451552b599cfaafd6236bd-le64.cache-7
7f3178442000-7f3178443000 r--s 00000000 fd:02 6686954                    /var/cache/fontconfig/ac68f755438cc3dc5a526084839fc7ca-le64.cache-7
7f3178443000-7f3178444000 r--s 00000000 fd:02 6686953                    /var/cache/fontconfig/f951a6bc01c50d58ac4af16a0108457e-le64.cache-7
7f3178444000-7f3178445000 r--s 00000000 fd:02 6686952                    /var/cache/fontconfig/8cab66d8f642305e525ba3e322d0979c-le64.cache-7
7f3178445000-7f3178446000 r--s 00000000 fd:02 6686951                    /var/cache/fontconfig/12513961c6e7090f8648812f9eaf65d6-le64.cache-7
7f3178446000-7f3178449000 r--s 00000000 fd:02 6686950                    /var/cache/fontconfig/e26bf336397aae6fcef4d3803472adec-le64.cache-7
7f3178449000-7f317844a000 r--s 00000000 fd:02 6686949                    /var/cache/fontconfig/f132fa2327207a6ac3298c0518879731-le64.cache-7
7f317844a000-7f317844b000 r--s 00000000 fd:02 6686947                    /var/cache/fontconfig/6fcb01a03a016cc71057b587cdea6709-le64.cache-7
7f317844b000-7f317844f000 r--s 00000000 fd:02 6686940                    /var/cache/fontconfig/8aa05f52519ebacbdf5713e01a6153b0-le64.cache-7
7f317844f000-7f3178450000 r--s 00000000 fd:02 6687086                    /var/cache/fontconfig/58e4d07e4f2af1648e5a91450aa7f4de-le64.cache-7
7f3178450000-7f3178451000 r--s 00000000 fd:02 6686938                    /var/cache/fontconfig/b887eea8f1b96e1d899b44ed6681fc27-le64.cache-7
7f3178451000-7f3178452000 r--s 00000000 fd:02 6686937                    /var/cache/fontconfig/860639f272b8b4b3094f9e399e41bccd-le64.cache-7
7f3178452000-7f3178453000 r--s 00000000 fd:02 6686936                    /var/cache/fontconfig/5d33f04e74a97395cf88bbd83847f1f1-le64.cache-7
7f3178453000-7f3178454000 r--s 00000000 fd:02 6686935                    /var/cache/fontconfig/df893b4576ad6107f9397134092c4059-le64.cache-7
7f3178454000-7f3178455000 r--s 00000000 fd:02 6686934                    /var/cache/fontconfig/1e1e03b57ed9f0c723c5aeafda46c3fb-le64.cache-7
7f3178455000-7f3178456000 r--s 00000000 fd:02 6686933                    /var/cache/fontconfig/900402270e15d763a6e008bb2d4c7686-le64.cache-7
7f3178456000-7f3178457000 r--s 00000000 fd:02 6686932                    /var/cache/fontconfig/47f48679023f44a4d1e44699a69464f6-le64.cache-7
7f3178457000-7f3178458000 r--s 00000000 fd:02 6686931                    /var/cache/fontconfig/2881ed3fd21ca306ddad6f9b0dd3189f-le64.cache-7
7f3178458000-7f3178459000 r--s 00000000 fd:02 6686930                    /var/cache/fontconfig/3c3fb04d32a5211b073874b125d29701-le64.cache-7
7f3178459000-7f317845a000 r--s 00000000 fd:02 6686929                    /var/cache/fontconfig/e61abf8156cc476151baa07d67337cae-le64.cache-7
7f317845a000-7f3178461000 r--s 00000000 fd:02 6687647                    /var/cache/fontconfig/b67b32625a2bb51b023d3814a918f351-le64.cache-7
7f3178461000-7f3178463000 r--s 00000000 fd:02 6686927                    /var/cache/fontconfig/d3379abda271c4acd2ad0c01f565d0b0-le64.cache-7
7f3178463000-7f3178464000 r--s 00000000 fd:02 6686926                    /var/cache/fontconfig/b4d0b56f766d89640448751fcd18ec1e-le64.cache-7
7f3178464000-7f3178469000 r--s 00000000 fd:02 6687119                    /var/cache/fontconfig/7ee6df7a8311986241317a58487e0145-le64.cache-7
7f3178469000-7f3178471000 r--s 00000000 fd:02 6687122                    /var/cache/fontconfig/7b312f204090bff0956e0e66992a6837-le64.cache-7
7f3178471000-7f3178473000 r--s 00000000 fd:02 6686924                    /var/cache/fontconfig/99a1ce9f8b6a0434aadb01d3779b0780-le64.cache-7
7f3178473000-7f3178486000 r--s 00000000 fd:02 6686921                    /var/cache/fontconfig/614d1caaa4d7914789410f6367de37ca-le64.cache-7
7f3178486000-7f3178491000 r--s 00000000 fd:02 6686920                    /var/cache/fontconfig/12b26b760a24f8b4feb03ad48a333a72-le64.cache-7
7f3178491000-7f3178498000 r--s 00000000 fd:02 6686917                    /var/cache/fontconfig/a116919b8bdb14ffaacd61d02e607fb8-le64.cache-7
7f3178498000-7f31784ba000 r--s 00000000 fd:00 278782                     /home/bilal/.cache/fontconfig/03a88d56ca3f81509d8a99276cd58db5-le64.cache-7
7f31784ba000-7f31788ba000 rw-p 00000000 00:00 0 
7f31788ba000-7f31788bb000 ---p 00000000 00:00 0 
7f31788bb000-7f31790bb000 rw-p 00000000 00:00 0                          [stack:22669]
7f31790bb000-7f3179132000 r-xp 00000000 fd:02 4071564                    /usr/lib64/libfreebl3.so
7f3179132000-7f3179331000 ---p 00077000 fd:02 4071564                    /usr/lib64/libfreebl3.so
7f3179331000-7f3179333000 r--p 00076000 fd:02 4071564                    /usr/lib64/libfreebl3.so
7f3179333000-7f3179334000 rw-p 00078000 fd:02 4071564                    /usr/lib64/libfreebl3.so
7f3179334000-7f3179338000 rw-p 00000000 00:00 0 
7f3179338000-7f317933f000 r-xp 00000000 fd:02 4070284                    /usr/lib64/libcrypt-2.22.so
7f317933f000-7f317953e000 ---p 00007000 fd:02 4070284                    /usr/lib64/libcrypt-2.22.so
7f317953e000-7f317953f000 r--p 00006000 fd:02 4070284                    /usr/lib64/libcrypt-2.22.so
7f317953f000-7f3179540000 rw-p 00007000 fd:02 4070284                    /usr/lib64/libcrypt-2.22.so
7f3179540000-7f317956e000 rw-p 00000000 00:00 0 
7f317956e000-7f3179574000 r-xp 00000000 fd:02 4071908                    /usr/lib64/libogg.so.0.8.2
7f3179574000-7f3179773000 ---p 00006000 fd:02 4071908                    /usr/lib64/libogg.so.0.8.2
7f3179773000-7f3179774000 r--p 00005000 fd:02 4071908                    /usr/lib64/libogg.so.0.8.2
7f3179774000-7f3179775000 rw-p 00000000 00:00 0 
7f3179775000-7f31797a0000 r-xp 00000000 fd:02 4072189                    /usr/lib64/libvorbis.so.0.4.7
7f31797a0000-7f31799a0000 ---p 0002b000 fd:02 4072189                    /usr/lib64/libvorbis.so.0.4.7
7f31799a0000-7f31799a1000 r--p 0002b000 fd:02 4072189                    /usr/lib64/libvorbis.so.0.4.7
7f31799a1000-7f31799a2000 rw-p 00000000 00:00 0 
7f31799a2000-7f31799ab000 r-xp 00000000 fd:02 4070637                    /usr/lib64/libltdl.so.7.3.1
7f31799ab000-7f3179baa000 ---p 00009000 fd:02 4070637                    /usr/lib64/libltdl.so.7.3.1
7f3179baa000-7f3179bab000 r--p 00008000 fd:02 4070637                    /usr/lib64/libltdl.so.7.3.1
7f3179bab000-7f3179bac000 rw-p 00009000 fd:02 4070637                    /usr/lib64/libltdl.so.7.3.1
7f3179bac000-7f3179bc0000 r-xp 00000000 fd:02 4070950                    /usr/lib64/libtdb.so.1.3.8
7f3179bc0000-7f3179dc0000 ---p 00014000 fd:02 4070950                    /usr/lib64/libtdb.so.1.3.8
7f3179dc0000-7f3179dc1000 r--p 00014000 fd:02 4070950                    /usr/lib64/libtdb.so.1.3.8
7f3179dc1000-7f3179dc2000 rw-p 00015000 fd:02 4070950                    /usr/lib64/libtdb.so.1.3.8
7f3179dc2000-7f3179dca000 r-xp 00000000 fd:02 4072191                    /usr/lib64/libvorbisfile.so.3.3.6
7f3179dca000-7f3179fc9000 ---p 00008000 fd:02 4072191                    /usr/lib64/libvorbisfile.so.3.3.6
7f3179fc9000-7f3179fca000 r--p 00007000 fd:02 4072191                    /usr/lib64/libvorbisfile.so.3.3.6Aborted (core dumped)
```

**Comment by gnunn1** [comment] 2016-01-14 00:17
This line in particular:
```
(terminix:22665): GLib-CRITICAL **: g_variant_get_int64: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT64)' failed
```
was causing a crash in Ubuntu and has been fixed, can you try the 0.35 version I just uploaded. Note there is a new issue with this version where if you set the encoding it fails so avoid changing that, but everything else in profiles will hopefully work.

**Comment by bil-elmoussaoui** [comment] 2016-01-14 00:19
Thanks for the quick fix & answers! i will try this tomorrow.

**Comment by gnunn1** [comment] 2016-01-14 00:30
I spoke too soon, I am able to reproduce this in Oracle Linux 7.2.  I'll investigate.

**Comment by gnunn1** [comment] 2016-01-14 23:49
Note this is fixed with a local patch to GtkD, GtkD should be updated shortly. Until it is, any builds done from scratch will still have this issue. See GtkD discussion on this issue here:

http://forum.gtkd.org/groups/GtkD/thread/336/

**Comment by bil-elmoussaoui** [comment] 2016-01-15 00:00
Thanks :+1:

**Comment by gnunn1** [comment] 2016-01-15 10:42
Hmm, turns out this is partially fixed, If you have the option "Use system colors as foreground and background" set you get the same problem. It is the same bug in GtkD, will fix it later today. 

Also, this problem looks like it it may be in  a few spots in GtkD, basically anywhere there is an out parameter. Having said that, these color related ones really highlight the issue because just moving the transparency slider back and forth causes a large number of these calls to be made. Will need a more comprehensive fix from GtkD.

**Comment by gnunn1** [comment] 2016-01-15 18:38
Pushed the fix for the other memory issue in the profile dialog in 0.36.1. However, since doing this right relies on a fix from GtkD I'm going to leave this issue open until then. I would appreciate some feedback from folks who had the crash issue if things are more stable now or if they still experience issues.

**Comment by gnunn1** [comment] 2016-01-17 20:28
Should be fixed now with the new version of GtkD. If memory crash issues persist please open a new issue.

**Closed by gnunn1** 2016-01-17 20:28 UTC
Labels: bug
