### ISSUE TITLE
terminix 1.5.0 crashes unexpectly

### ISSUE THREAD

**Issue by nean-and-i** [gnunn1/terminix#806] opened 2017-02-28 14:28 UTC
seems something is strange, after a few crashes I reverted to 1.4.3.
sorry, could find time to debug it any further.
(I'm using the zip https://github.com/gnunn1/terminix/releases/download/1.5.0/terminix.zip)

# grep terminix /var/log/syslog
Feb 28 11:18:07 host kernel: [ 3918.335897] traps: terminix[4290] general protection ip:5d77ca sp:7ffcaf21cdc0 error:0 in terminix[400000+8e2000]
Feb 28 15:06:21 host kernel: [17613.087440] terminix[9456]: segfault at 7f32ca15e000 ip 00007f32ca15e000 sp 00007ffd6c60e7d8 error 15
Feb 28 15:14:35 host kernel: [18107.019283] traps: gnome-terminal[18611] general protection ip:5d77ca sp:7ffcbd0ebe60 error:0 in terminix[400000+8e2000]

# uname -a
Linux atls000002 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by gnunn1** [comment] 2017-02-28 15:15
Duplicate of #803, if someone could test it then I could roll out 1.5.2.

**Closed by gnunn1** 2017-02-28 15:15 UTC

**Comment by nean-and-i** [comment] 2017-03-04 10:21
I'll be your man ;-) 

I heavily use it for daily work (international ISP),... 
so, I'd recognise any issue quite soon, but sometimes I can't find time for time consuming debugging, but will do my best ;-) 

fyi, the scrollbar issue also still exists, but only on very rare basis, it seems only on certain window sizes. 

However, it's becoming the very best terminal app in the gnome world, love it, and a special "thank you" for heaving an ear for the community and testers! 
It should get much more appreciation and attention to the fedora and gnome developers! 

cheers, 
nean
