### ISSUE TITLE
Quake mode switch disables app menu/icon under GNOME 3.20

### ISSUE THREAD

**Issue by anassahmed** [gnunn1/terminix#471] opened 2016-09-11 18:22 UTC
I'm using Fedora 24 + GNOME 3.20 + Wayland. I assigned a hotkey for `terminx --quake` and it worked for the first time amazingly.

Then when I switched back to it (toggled the window visibility using the hotkey), the app menu (in GNOME Shell top bar) has become one option (Quit) and the app name became "terminix" (starting with small letter) with a generic app icon!

Before switching the visibility:
![screenshot from 2016-09-11 20-20-31](https://cloud.githubusercontent.com/assets/928614/18419523/a3213f2c-7865-11e6-8422-e985bce30c83.png)

After switching the visibility:
![screenshot from 2016-09-11 20-20-14](https://cloud.githubusercontent.com/assets/928614/18419524/a324f536-7865-11e6-8659-946b030430b5.png)

**Comment by gnunn1** [comment] 2016-09-11 18:31
I checked in some new code about an hour ago, can you check that out and see if it fixes the issue as it seems fine to me. Still have a focus issue to work on though.

**Comment by gnunn1** [comment] 2016-09-11 22:43
I spoke too soon, I can replicated this under Wayland. No clue as to what the solution is though, It will need more investigation. Might also be a bug with gnome-shell.

**Comment by gnunn1** [comment] 2016-09-12 22:41
Filed an upstream bug for this:

 https://bugzilla.gnome.org/show_bug.cgi?id=771329

**Comment by gnunn1** [comment] 2016-09-13 16:38
So upstream responded, doesn't look the two methods I'm using in x11 to hide from the pager and taskbar work in Wayland. The other issue is there may be a bug in Wayland with the appmenu when a window is hidden and shown, if the hide from taskbar worked you would never see the appmenu in Wayland so it would be a non-issue. 

I'll build a simple reproducer for the hide/show and open a new bug against gnome-shell if I can reproduce it,

**Comment by gnunn1** [comment] 2016-09-15 00:00
I notice lollypop has issues as well with the appmenu under Wayland when you set the option for continuous playback where the app keeps running.

**Comment by gnunn1** [comment] 2016-09-15 13:53
One more upstream bug filed:

https://bugzilla.gnome.org/show_bug.cgi?id=771492

**Comment by anassahmed** [comment] 2016-09-18 22:11
I've switched to X11 with the latest code (1.3.0) and tested it again but I noticed that there's no app menu at all!

![screenshot from 2016-09-18 23-53-09](https://cloud.githubusercontent.com/assets/928614/18619464/d46265e8-7e05-11e6-8263-101135b6a275.png)

**Comment by gnunn1** [comment] 2016-09-18 22:22
Yes, that's always been the intent as nothing in the application menu is very useful since the quake window is an always-on-top window. Opening things like Preferences and Shortcuts makes them appear under the quake'ed terminix window. I'm open to having a discussion about it though.

Unfortunately Wayland doesn't respect the taskbar and pager hints which is the only reason it shows up there.

**Comment by anassahmed** [comment] 2016-09-18 23:08
Oh, I didn't know that because I used it for the first time under Wayland. :smile: 

I don't have issue with that really, but it was only an observation.

**Comment by gnunn1** [comment] 2016-09-18 23:10
No worries, I'll freely admit I'm not a user of drop down terminals so the way features are presented may not be aligned with users expectations, hence why I'm happy to have a discussion about it.

Anyway, I'm going to close this issue since under Wayland it appears to be an upstream issue since I can reproduce it with three different applications (Terminix, Geary and Lollypop).

**Closed by gnunn1** 2016-09-18 23:10 UTC
Labels: bug, Upstream
