### ISSUE TITLE
Crash on insert password

### ISSUE THREAD

**Issue by Salamandar** [gnunn1/terminix#512] opened 2016-10-02 16:08 UTC
Just installed Terminix 1.3.0 on Archlinux !
I configured the insert passwd shortcut, but when doing the shortcut I get (GDB backtrace) : 
```
(terminix:30289): GLib-CRITICAL **: g_main_loop_is_running: assertion 'g_atomic_int_get (&loop->ref_count) > 0' failed

Thread 1 "terminix" received signal SIGSEGV, Segmentation fault.
0x00007fff00000001 in ?? ()
(gdb) bt
#1  0x0000000001c88180 in  ()
#2  0x0000000001c883c0 in  ()
#3  0x0000000001c88180 in  ()
#4  0x00007fffef023f48 in  () at /usr/lib/libgtk-3.so.0
#5  0x00007ffff2c8ca18 in g_object_run_dispose () at /usr/lib/libgobject-2.0.so.0
#6  0x0000000000a78aae in gtk.Widget.Widget.destroy() ()
#7  0x000000000097f21c in gx.terminix.terminal.terminal.Terminal.createActions(gio.SimpleActionGroup.SimpleActionGroup).__dgliteral22(glib.Variant.Variant, gio.SimpleAction.SimpleAction) ()
#8  0x00000000009e5e39 in gio.SimpleAction.SimpleAction.callBackActivate(gtkc.giotypes.GSimpleAction*, gtkc.glibtypes.GVariant*, gio.SimpleAction.SimpleAction) ()
#9  0x00007ffff2c86105 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff2c98bd2 in  () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff2ca1afc in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff2ca1edf in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff255311d in  () at /usr/lib/libgio-2.0.so.0
#14 0x00007fffeed9589e in  () at /usr/lib/libgtk-3.so.0
#15 0x00007fffeed958d4 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007fffeed958d4 in  () at /usr/lib/libgtk-3.so.0
#17 0x00007fffeedacfd5 in  () at /usr/lib/libgtk-3.so.0
#18 0x00007fffef02b656 in gtk_window_activate_key () at /usr/lib/libgtk-3.so.0
#19 0x00007fffef02b721 in  () at /usr/lib/libgtk-3.so.0
#20 0x00007fffeeec5831 in  () at /usr/lib/libgtk-3.so.0
#21 0x00007ffff2c86334 in  () at /usr/lib/libgobject-2.0.so.0
#22 0x00007ffff2ca12c1 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff2ca1edf in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#24 0x00007fffef007b0c in  () at /usr/lib/libgtk-3.so.0
#25 0x00007fffeeec2a99 in  () at /usr/lib/libgtk-3.so.0
#26 0x00007fffeeec48e2 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#27 0x00007ffff1fe7755 in  () at /usr/lib/libgdk-3.so.0
#28 0x00007ffff2014722 in  () at /usr/lib/libgdk-3.so.0
#29 0x00007ffff62bb627 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#30 0x00007ffff62bb890 in  () at /usr/lib/libglib-2.0.so.0
#31 0x00007ffff62bb93c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#32 0x00007ffff254aacd in g_application_run () at /usr/lib/libgio-2.0.so.0
#33 0x00000000009c26c0 in gio.Application.Application.run(immutable(char)[][]) ()
#34 0x00000000008ecfb6 in D main ()
```

**Comment by gnunn1** [comment] 2016-10-02 16:38
Unfortunately I'm not able to reproduce, are you using GTK 3.20?

**Comment by Salamandar** [comment] 2016-10-03 17:20
Yes, Gtk+3.20.9.

**Comment by gnunn1** [comment] 2016-10-03 17:33
Thanks, I have a suspicion. If I compile a special version for you would you be willing to test it out?

**Comment by gnunn1** [comment] 2016-10-13 23:45
No response from OP, I've modified the code to address this. Is there anyone with this issue that is willing to try a test build, if not I'm going to close this.

**Comment by Salamandar** [comment] 2016-10-14 08:06
Thats strange, I responded that I could test it but thats not been saved by github. So yes, I can test it.

**Comment by gnunn1** [comment] 2016-10-15 18:23
I was able to reproduce it in a VM, should be fixed now.

**Closed** 2016-10-15 18:23 UTC
Labels: bug, Can't Reproduce

**Comment by Salamandar** [comment] 2016-10-17 11:25
Fix confirmed in the last Git rev :) Thanks !
