### ISSUE TITLE
Missing window controls in Ubuntu (Yakkety Yak)

### ISSUE THREAD

**Issue by Udara-U3** [gnunn1/terminix#453] opened 2016-08-22 08:50 UTC
Missing window controls such as **Minimize and Maximize** in Ubuntu (Yakkety Yak) with Latest **Terminix** Stable 1.2.0 release.

![terminix_issue](https://cloud.githubusercontent.com/assets/12265797/17848778/71d8a9b4-6866-11e6-8cd3-1f3aab6b33e7.png)

**Comment by gnunn1** [comment] 2016-08-22 11:24
I think this is expected behavior, Terminix uses CSD so it behaves like gnome applications which haven't been patched by Ubuntu. You can disable the CSD by using dcong-editor and setting the disable-csd to true in com/gexperts/Terminix

**Comment by Udara-U3** [comment] 2016-08-22 11:48
After disabling CSD, Tereminix is fully weird :confused: Any idea ?

  ![screenshot from 2016-08-22 15-46-56](https://cloud.githubusercontent.com/assets/12265797/17853793/d0d94a54-687f-11e6-866a-92247a65180f.png)

**Comment by gnunn1** [comment] 2016-08-22 11:55
Yeah, I screwed up. I probably didn't do enough testing with the CSD disabled when I did the re-design. I'll get my Ubuntu VM fired up and have a look in the next couple of days.

One other thought, if you turn the CSD back on again, can you use the gnome tweak tool to add the missing window controls by enabling the Maximize and Minimize buttons?

![screenshot from 2016-08-22 07-54-30](https://cloud.githubusercontent.com/assets/9358238/17853974/b7bf70d0-683d-11e6-9554-8545063428cb.png)

**Comment by Udara-U3** [comment] 2016-08-22 11:58
@gnunn1 I have already enabled those window controls, former Screenshot with enabled window controls. Btw Thank you for your support, :+1:  Hopefully this Bug will fix in the future :smile:

**Comment by gnunn1** [comment] 2016-08-24 00:53
BTW, what theme are you using?

**Comment by gnunn1** [comment] 2016-08-24 01:27
Answering my own question, that theme is Adapta and it looks like it has some issues as other themes render it fine. Having said that, I'll freely I haven't spent much time optimizing the look of terminix when the CSD is disabled so I'll need to look into it.

**Comment by Udara-U3** [comment] 2016-08-24 04:18
Yeah It's **Adapta theme** I'll check that out. Thank you.

**Comment by gnunn1** [comment] 2016-08-24 12:15
I've checked in a change that greatly improves the look when disable-csd is enabled:

![screenshot from 2016-08-24 08-14-05](https://cloud.githubusercontent.com/assets/9358238/17930185/f02ec222-69d2-11e6-9c96-1c85a7519b35.png)

**Comment by Udara-U3** [comment] 2016-08-24 12:53
Ohh why is that, :confused: I don't know maybe it's Adapta issue.

**Comment by gnunn1** [comment] 2016-08-24 13:33
It's just the way Adapta styles buttons, it behaves differently when the button is on a headerbar versus other GTK widgets. I re-worked the code to always use a headerbar, probably for the best to maintain theme compatibility. 

I'll have a look at the minimize, maximize button issue when I get a chance.

**Comment by Udara-U3** [comment] 2016-08-25 08:09
Ok thanks :smile:

**Comment by gnunn1** [comment] 2016-09-15 13:54
I'm having issues getting 16.10 working in a VM, @alexwhitman any chance you are using Ubuntu 16.10 and can test to see if this is still an issue?

**Comment by alexwhitman** [comment] 2016-09-15 14:12
Sorry, running 16.04 both at home and at work.  I might have a bit of time to try and get in running in a VM over the weekend if you're still having issues by then.

**Comment by gnunn1** [comment] 2016-09-15 14:14
@alexwhitman Thanks, I'll give it another go tonite just feeling lazy and hoping you might already be there :)

**Comment by gnunn1** [comment] 2016-09-20 22:08
OK finally got my VM sorted out and tested it, I cannot reproduce as I get all the window buttons (min, max, close) as expected. See picture:

![screenshot from 2016-09-20 18-05-25](https://cloud.githubusercontent.com/assets/9358238/18690657/37d439aa-7f5d-11e6-81c4-53a1f162cd17.png)

**Closed by gnunn1** 2016-09-20 22:08 UTC
Labels: bug, question

**Comment by Udara-U3** [comment] 2016-09-21 04:13
@gnunn1 Please update Ubuntu packages (Yakkety) including this fix 😄
