### ISSUE TITLE
Option to reduce mouse area for session switcher

### ISSUE THREAD

**Issue by zoqaeski** [gnunn1/terminix#142] opened 2016-03-15 01:55 UTC
I have mouse support enabled in tmux and neovim, among others, and I'm finding that the focus area for switching sessions and displaying previews is really wide, preventing me from clicking within the terminal window underneath. Can an option be provided to either reduce this area, or disable it?

**Comment by gnunn1** [comment] 2016-03-15 02:01
I assume you are talking about the sidebar? It only appears when you explicitly invoke it and it disappears automatically when you select a session or close it (via escape, sidebar shortcut or clicking somewhere outside it) so I'm not sure why it is a problem for you? Can you elaborate more on the issue.

**Comment by kpocius** [comment] 2016-03-15 08:25
I ran into the same issue on Fedora 23, using terminix-0.53.0-4.1.x86_64
The problem is that the first time you invoke sidebar, the whole area where sidebar appears becomes "clickable". Every time after the first invocation, trying to click anywhere in the terminal where sidebar used to be, brings it back up.

**Comment by arshavindn** [comment] 2016-03-15 08:30
@kpocius is it your problem? https://www.youtube.com/watch?v=Jj27T4unjqs

**Comment by kpocius** [comment] 2016-03-15 10:03
Yes, exactly that.

**Comment by arshavindn** [comment] 2016-03-15 13:37
I used to have that issue, but dont know why it's gone now, so I closed it.
https://github.com/gnunn1/terminix/issues/126

**Comment by gnunn1** [comment] 2016-03-15 13:48
I need some help to reproduce this. When you open the sidebar for the first time, how are you closing it? Are you clicking somewhere outside the sidebar, pressing escape, pressing the sidebar shortcut, etc? I suspect it's not letting go of the mouse grab in some circumstance.

**Comment by gnunn1** [comment] 2016-03-15 14:13
OK I am able to reproduce the issue artificially by commenting out my call to grabRemove when the sidebar is hidden. I suspect the suspect is getting closed behind my back for some reason, I've added an event handler that takes care of removing the grab when the widget is unmapped so hopefully that will fix the issue.

If someone who has this issue could build from source and test I'd appreciate it.

**Comment by kpocius** [comment] 2016-03-15 19:01
Still getting the issue after building from master. Is there any additional debugging info I can provide?

**Comment by gnunn1** [comment] 2016-03-15 20:05
@kpocius Assuming you made a normal build using ```dub build``` you should see a lot of trace output if you run Terminix from another terminal. One thing to look for are these messages:

```
** Show sidebar
** Hide sidebar
** Sidebar unmapped
```

If you see a Show sidebar without a corresponding hide or unmapped, it would indicate that the sidebar grab is still in effect, do you see that at all?

Also, what distro and GTK version are you using?

**Comment by kpocius** [comment] 2016-03-15 20:59
When I start terminix and click sidebar button twice (to reveal and then to hide it), I get those messages. Then I click in the general area where the sidebar was, and get the same messages again. Here's the full output of my test:

```
2016-03-15T22:46:59.479:app.d:main:23 Starting terminix...
2016-03-15T22:46:59.479:app.d:main:31 No terminix UUID found
2016-03-15T22:46:59.479:app.d:main:50 Creating app
2016-03-15T22:46:59.480:app.d:main:54 Running application...
2016-03-15T22:46:59.556:application.d:onAppStartup:241 Startup App Signal
2016-03-15T22:46:59.556:util.d:findResource:235 looking for resource /usr/local/share/terminix/resources/terminix.gresource
2016-03-15T22:46:59.556:util.d:findResource:235 looking for resource /usr/share/terminix/resources/terminix.gresource
2016-03-15T22:46:59.556:util.d:findResource:239 Resource found and registered /usr/share/terminix/resources/terminix.gresource
2016-03-15T22:46:59.559:application.d:onAppStartup:244 Monitoring shortcuts
2016-03-15T22:46:59.560:application.d:applyPreferences:280 Default menu accelerator is F10
2016-03-15T22:46:59.562:application.d:onCommandLine:215 App processing command line
2016-03-15T22:46:59.562:cmdparams.d:this:104 Command line parameters:
2016-03-15T22:46:59.562:cmdparams.d:this:105 	working-directory=
2016-03-15T22:46:59.562:cmdparams.d:this:106 ["\tsession="]
2016-03-15T22:46:59.562:cmdparams.d:this:107 	profile=
2016-03-15T22:46:59.562:cmdparams.d:this:108 	action=
2016-03-15T22:46:59.563:cmdparams.d:this:109 	execute=
2016-03-15T22:46:59.563:application.d:onCommandLine:228 Activating app
2016-03-15T22:46:59.563:application.d:onAppActivate:234 Activate App Signal
2016-03-15T22:46:59.566:appwindow.d:updateVisual:371 Setting rgba visual
2016-03-15T22:46:59.641:terminal.d:setupDragAndDrop:1151 Setting up drag and drop
2016-03-15T22:46:59.642:terminal.d:setupDragAndDrop:1174 Drag and drop completed
2016-03-15T22:46:59.642:terminal.d:this:1494 Apply preferences
2016-03-15T22:46:59.644:terminal.d:this:1496 Profile Event Handler
2016-03-15T22:46:59.644:terminal.d:this:1498 Finished creation
2016-03-15T22:46:59.645:terminal.d:updateTitle:718 Terminal not initialized yet, no path available
2016-03-15T22:46:59.645:terminal.d:initTerminal:1509 Initializing Terminal
2016-03-15T22:46:59.647:terminal.d:spawnTerminalProcess:1117 Argument: /bin/bash
2016-03-15T22:46:59.652:terminal.d:initTerminal:1513 Set VTE Size for rows 24
2016-03-15T22:46:59.652:terminal.d:initTerminal:1514 Set VTE Size for columns 80
2016-03-15T22:46:59.653:terminal.d:initTerminal:1517 Terminal initialized
2016-03-15T22:46:59.653:terminal.d:updateTitle:718 Terminal not initialized yet, no path available
2016-03-15T22:46:59.659:appwindow.d:__dgliteral1:135 Switched Sessions
2016-03-15T22:46:59.659:session.d:focusRestore:965 Restoring focus to terminal
2016-03-15T22:46:59.660:appwindow.d:__dgliteral1:135 Switched Sessions
2016-03-15T22:46:59.660:session.d:focusRestore:965 Restoring focus to terminal
2016-03-15T22:46:59.947:terminal.d:onTerminalWidgetFocusIn:894 Terminal gained focus 5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:46:59.978:terminal.d:onTerminalWidgetFocusOut:911 Terminal lost focus5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:00.051:terminal.d:onTerminalWidgetFocusIn:894 Terminal gained focus 5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:00.331:terminal.d:__dgliteral1:607 Window title changed, pid=20945 'karolis@m1330:~'
2016-03-15T22:47:00.332:terminal.d:updateTitle:716 Current directory is
2016-03-15T22:47:00.332:terminal.d:__dgliteral2:611 Icon title changed, pid=20945 'karolis@m1330:~'
2016-03-15T22:47:00.332:terminal.d:updateTitle:716 Current directory is
2016-03-15T22:47:00.332:terminal.d:__dgliteral3:613 Current directory changed, pid=20945 '/home/karolis'
2016-03-15T22:47:00.333:terminal.d:updateTitle:716 Current directory is /home/karolis
2016-03-15T22:47:02.635:appwindow.d:__dgliteral4:255 Sidebar action activated true
2016-03-15T22:47:02.635:appwindow.d:__dgliteral4:260 Toggle sidebar on
2016-03-15T22:47:02.635:sidebar.d:populateSessions:133 Populating sidebar sessions
2016-03-15T22:47:02.636:cairo.d:getDrawableWidgetImage:90 Original: 735, 469
2016-03-15T22:47:02.636:cairo.d:getDrawableWidgetImage:93 Factor: 0,200000, New: 147, 93
2016-03-15T22:47:02.644:cairo.d:getWidgetImage:40 Total time getting thumbnail: 8 msecs
2016-03-15T22:47:02.652:sidebar.d:setRevealChild:188 ** Show sidebar
2016-03-15T22:47:02.654:terminal.d:onTerminalWidgetFocusOut:911 Terminal lost focus5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:03.915:sidebar.d:onButtonPress:65 ** Sidebar button press
2016-03-15T22:47:03.916:appwindow.d:__dgliteral2:149 Session selected
2016-03-15T22:47:03.916:appwindow.d:__dgliteral4:255 Sidebar action activated false
2016-03-15T22:47:03.917:sidebar.d:__dgliteral1:116 ** Sidebar unmapped
2016-03-15T22:47:03.917:sidebar.d:setRevealChild:191 ** Hide sidebar
2016-03-15T22:47:03.917:session.d:focusRestore:965 Restoring focus to terminal
2016-03-15T22:47:03.918:terminal.d:onTerminalWidgetFocusIn:894 Terminal gained focus 5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:03.918:session.d:focusRestore:965 Restoring focus to terminal
2016-03-15T22:47:06.866:sidebar.d:onButtonPress:65 ** Sidebar button press
2016-03-15T22:47:06.867:appwindow.d:__dgliteral2:149 Session selected
2016-03-15T22:47:06.867:appwindow.d:__dgliteral4:255 Sidebar action activated true
2016-03-15T22:47:06.867:appwindow.d:__dgliteral4:260 Toggle sidebar on
2016-03-15T22:47:06.867:sidebar.d:populateSessions:133 Populating sidebar sessions
2016-03-15T22:47:06.868:cairo.d:getDrawableWidgetImage:90 Original: 735, 469
2016-03-15T22:47:06.868:cairo.d:getDrawableWidgetImage:93 Factor: 0,200000, New: 147, 93
2016-03-15T22:47:06.872:cairo.d:getWidgetImage:40 Total time getting thumbnail: 4 msecs
2016-03-15T22:47:06.875:sidebar.d:setRevealChild:188 ** Show sidebar
2016-03-15T22:47:06.876:terminal.d:onTerminalWidgetFocusOut:911 Terminal lost focus5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:06.876:session.d:focusRestore:965 Restoring focus to terminal
2016-03-15T22:47:06.877:terminal.d:onTerminalWidgetFocusIn:894 Terminal gained focus 5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:08.676:sidebar.d:onButtonPress:65 ** Sidebar button press
2016-03-15T22:47:08.677:appwindow.d:__dgliteral2:149 Session selected
2016-03-15T22:47:08.677:appwindow.d:__dgliteral4:255 Sidebar action activated false
2016-03-15T22:47:08.679:sidebar.d:__dgliteral1:116 ** Sidebar unmapped
2016-03-15T22:47:08.679:sidebar.d:setRevealChild:191 ** Hide sidebar
2016-03-15T22:47:08.680:terminal.d:onTerminalWidgetFocusOut:911 Terminal lost focus5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:08.680:session.d:focusRestore:965 Restoring focus to terminal
2016-03-15T22:47:08.681:terminal.d:onTerminalWidgetFocusIn:894 Terminal gained focus 5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:08.681:session.d:focusRestore:965 Restoring focus to terminal
2016-03-15T22:47:10.960:terminal.d:onTerminalChildExited:794 Exit code received is 0
2016-03-15T22:47:10.960:session.d:removeTerminal:226 Removing terminal 5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:10.961:terminal.d:onTerminalWidgetFocusOut:911 Terminal lost focus5747b0a8-8e1f-40da-93fb-c6c7c23f9462
2016-03-15T22:47:10.967:session.d:removeTerminal:253 There are 0 terminals left
2016-03-15T22:47:10.967:session.d:removeTerminal:255 No more terminals, requesting session be closed
2016-03-15T22:47:10.968:appwindow.d:removeSession:408 No more sessions, closing AppWindow
2016-03-15T22:47:10.968:appwindow.d:closeSession:428 Session closed
2016-03-15T22:47:10.968:terminal.d:__dgliteral2:1471 Terminal destroy
2016-03-15T22:47:10.978:application.d:onAppShutdown:262 Quit App Signal
2016-03-15T22:47:10.979:app.d:main:56 App completed...
```

I'm running Fedora 23 with gtk3-3.18.9-1.fc23.x86_64

**Closed** 2016-03-16 03:16 UTC
Labels: bug

**Comment by gnunn1** [comment] 2016-03-16 03:17
I was able to reproduce it in a VM under Fedora 23 and fix it there. Please build from source and test my fix to confirm it works. Any problems please feel free to re-open this issue.

**Comment by kpocius** [comment] 2016-03-16 07:28
Works like a charm! Thank you.
