### ISSUE TITLE
not sourcing /etc/profile.d for $PATH

### ISSUE THREAD

**Issue by brittyazel** [gnunn1/terminix#193] opened 2016-03-28 18:34 UTC
Let me preface this by saying that I have no idea if this is a Terminix issue. That being said, when using Gnome-Terminal, whenever I open the terminal my $PATH is set to: `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
`
Which is correct and properly sourced. However, when I initially open Terminix, my path is set to:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin`
Which is not sourcing /etc/profile.d at all. A solution to this is to edit the profile and say "run command as a login shell", which will then cause Terminix to properly source /etc/sources.d and the path will correctly be set as above.

Anyway, I swear I had this issue before also using Gnome-Terminal where my $PATH would be set wrong, but I can't seem to replicate it anymore, and only Terminix expresses this error. Odd.

**Comment by gnunn1** [comment] 2016-03-28 18:38
Just to rule out the obvious, you don't have login shell enabled in gnone-terminal?

**Comment by brittyazel** [comment] 2016-03-28 18:39
Yes this was without login shell enabled in gnome-terminal

**Comment by brittyazel** [comment] 2016-03-28 18:39
I even rebooted for safe measure, and still the issue only reared its head in Terminix

**Comment by gnunn1** [comment] 2016-03-29 13:11
I'm happy to have a look at it but I've never heard of /etc/sources.d and I don't have it on my Arch system, what distribution are you using? Do you have a link that describes what it is used for as googling didn't turn up much?

**Comment by brittyazel** [comment] 2016-03-29 13:53
SORRY! Huge mistake, the folder is /etc/profile.d, not sources.d. I was working on a different project and somehow mixed up the folder name in my head. I'm sorry if that wasted your time!

I too am running archlinux. From my understanding /etc/profile.d is a directory that contains a series of shell scripts, one function of which is to be sourced for appending new directories to the $PATH variable.

**Comment by gnunn1** [comment] 2016-03-29 13:56
No worries, I should have paid more intention to the title.

Anyway, this is a known issue I think with Arch and some other distributions. See the FAQ below, while it talks about it in regards to the /etc/profile.d/vte.sh script the issue is the same:

https://github.com/gnunn1/terminix/wiki/VTE-Configuration-Issue

**Comment by brittyazel** [comment] 2016-03-29 14:06
Weird, I see now why enabling login-shell will rectify this issue. Here's the thing though, why is my Gnome-Terminal setting the path correctly now with/without login shell turned on? The whole issue that you described in the wiki seems now to only apply to Terminix's use of VTE and not Gnome-Terminal's use of VTE (under archlinux)

But like I said before, I definitely remember having this issue on Gnome-Terminal in the past, I just can't replicate it anymore. Did they potentially fix this issue finally? I know there was recently a couple of updates to VTE

**Comment by gnunn1** [comment] 2016-03-29 14:43
@brittyazel I don't think they've done anything on their side to fix it since on my system it's broken for gnome-terminal. Maybe do some googling for the issue with respect to gnome-terminal and see if you stumble on something that refreshes your memory of how you fixed it?

**Comment by brittyazel** [comment] 2016-03-30 00:07
Weird you are right, on two of my computers Gnome-Terminal is sourcing the scripts properly and setting the path without the need for "login shell". But on my third computer (which is virtually identical) Gnome-Terminal is not working properly. The worst part is that I have no idea what I did...I don't tend to mess with things very much

**Comment by gnunn1** [comment] 2016-03-30 00:51
That sucks, are you OK if I close this because it doesn't appear to be an issue with terminix?

**Comment by brittyazel** [comment] 2016-03-30 01:11
Yeah go for it. Quick question though, are the arch devs aware of the issues with the way vte3 is packaged? Is there any reason for me to ask them to adjust their packaging to solve this

**Comment by gnunn1** [comment] 2016-03-30 01:38
I assume so, see the wiki here which makes the behavior crystal clear:

https://wiki.archlinux.org/index.php/bash#Configuration_files

**Closed by gnunn1** 2016-03-30 01:38 UTC
