### ISSUE TITLE
Leftover scrollbar

### ISSUE THREAD

**Issue by eda2z** [gnunn1/terminix#394] opened 2016-07-13 14:14 UTC
I'm not sure if this is a terminix problem or gnome, but it's very minor -- I'm on the latest gnome 3.20 from Arch linux.  I'm not sure if all of the steps are necessary:

1. Open a new window and expand it down.
2. Split the window horizontally
3. Run several ls commands in the top window which cause the scrollbar to change
4. Switch to the lower window and run several ls commands to change its scrollbar
5. Close the lower window (either Ctrl+D or the "X" icon)

You should see some leftover scrollbar from the lower window below the scrollbar of the upper window.  Note that this leftover scrollbar does disappear if terminix looses the focus -- in my case I'm using "mouse" focus mode.

**Comment by gnunn1** [comment] 2016-07-13 22:57
I cannot reproduce this on GTK 3.20, what distro and GTK version are you using? Also, are you using a custom theme, if so try Adwaita and see if you can still reproduce the issue.

**Comment by eda2z** [comment] 2016-07-14 01:44
Arch linux;
gtk3 3.20.6-1;
Adwaita for gtk+ theme, icons and cursor

I am also using the Global Dark Theme but that doesn't seem to make a difference.

**Comment by gnunn1** [comment] 2016-07-14 01:45
Can you take a screenshot of the problem and attach please

**Comment by gnunn1** [comment] 2016-07-14 01:46
Oh and is this the stable or git package, I'm testing on the latest in git

**Comment by eda2z** [comment] 2016-07-14 14:51
![screenshot from 2016-07-14 09-44-50](https://cloud.githubusercontent.com/assets/6683633/16843687/e4eadc02-49a7-11e6-8e3c-1806fea76fa3.png)

A screenshot should be attached.  A couple of things:

1.  I did upgrade to the git version before the screenshot
2.  The "anomaly" did not occur on the first try but it did on subsequent ones -- closing the entire window and opening a new one
3.  The screenshot should also show my gtk versions
4.  If the only window on the screen is the one with the "tail", I could drag it around and the "tail" would follow

Let me know if you need anything else.  I am a retired software developer (not manager) and have a lot of free time.

**Comment by gnunn1** [comment] 2016-07-14 15:34
I'm pretty sure that's a GTK bug and not specifically a Terminix bug, I'll see if I can reproduce tonight and if so open a bug report in Gnome's bugzilla.

I'm always looking for help with terminix, if you want to want to write some code and work on the project just let me know as there's lots that needs doing.

**Comment by gnunn1** [comment] 2016-07-15 00:32
I can reproduce this and have opened an upstream bug:

https://bugzilla.gnome.org/show_bug.cgi?id=768829

**Comment by gnunn1** [comment] 2016-07-15 22:55
Closing this here since it is an upstream issue.

**Closed by gnunn1** 2016-07-15 22:55 UTC
Labels: bug, Upstream
