### ISSUE TITLE
Cannot move tiles

### ISSUE THREAD

**Issue by xisberto** [gnunn1/terminix#332] opened 2016-05-16 13:04 UTC
I don't know if this is a preference I have marked, or if it was removed.

I cannot move tiles anymore. It was possible before: https://i.ytimg.com/vi/z6COBUviMtY/maxresdefault.jpg

**Comment by gnunn1** [comment] 2016-05-16 13:33
Can you provide some info about your environment? Distro, GTK version, X11 or Wayland?

Also, any chance it's a case of the drawing not happening versus drop not happening? i.e. If you drag a terminal over the other ones, it should highlight the quadrant where the drop will happen. Is it possible this highlighting is broken but the actual drop still works?

**Comment by xisberto** [comment] 2016-05-16 14:36
I'm using archlinux with Gnome 3.20 under Wayland.

Drawing from the tiles titles does nothing. The highlight doesn't appear at all.

**Comment by gnunn1** [comment] 2016-05-16 14:41
Thanks, I just tried testing it on master and dragging is completely broken, I must have done something when working on the transparency issues. Are you using the ```terminix``` package or ```terminix-git```?

**Comment by xisberto** [comment] 2016-05-16 15:11
I'm using `terminix`

**Comment by gnunn1** [comment] 2016-05-16 15:19
Thanks, just quickly tried it on GTK 3.18 and it's still working fine there. Now 9 times out of 10 the problem is something I've done, but in this case I wonder if an update in GTK broke something as there was a recent update in Arch on May 11th. I'll investigate some more tonite.

**Comment by gnunn1** [comment] 2016-05-16 15:28
Alright I couldn't resist trying this quickly, downgrading to ```gtk3 3.20.3-4``` fixes the problem. I'll open a bug report for GTK.

**Comment by bil-elmoussaoui** [comment] 2016-05-16 15:35
It's a GTK issue! Happens with Plank too

**Comment by gnunn1** [comment] 2016-05-16 15:38
Opened bug https://bugzilla.gnome.org/show_bug.cgi?id=766522 for it.

**Comment by gnunn1** [comment] 2016-05-16 19:44
Thanks @bil-elmoussaoui, I see at least one other bug report for this in the gtk+ bugzilla. Closing this issue since it appears to be a GTK problem.

**Closed by gnunn1** 2016-05-16 19:44 UTC
Labels: bug

**Comment by bil-elmoussaoui** [comment] 2016-05-19 20:28
Update : A fix was released on gtk3 3.20.5-1! just received the update on arch:)
