### ISSUE TITLE
Graphical issues when using the dim option on unfocused terminals

### ISSUE THREAD

**Issue by Boiethios** [gnunn1/terminix#288] opened 2016-05-02 09:50 UTC
When I split the terminal :
![capture d ecran de 2016-05-02 11-44-46](https://cloud.githubusercontent.com/assets/18555389/14951762/af4737ec-105b-11e6-8bd7-02a875e2dd01.png)

When I open the menu at once, and close it :
![capture d ecran de 2016-05-02 11-44-59](https://cloud.githubusercontent.com/assets/18555389/14951771/c1f05fae-105b-11e6-833a-2785613dcb1e.png)

After switching terminal : this is how the menu shows when opened :
![capture d ecran de 2016-05-02 11-45-08](https://cloud.githubusercontent.com/assets/18555389/14951803/ffbde2d4-105b-11e6-94e1-f9757428a6d2.png)

**Comment by gnunn1** [comment] 2016-05-02 13:18
Thanks for reporting this. Can you provide the GTK version and distro you are using as I'm not experiencing any of these issues myself in 3.20. I'll try in my Fedora 23 VM when I get home from work, but more info about your environment would be helpful to track this down.

**Comment by Boiethios** [comment] 2016-05-02 13:27
- Debian testing
- libgtk 3.18.9-1
- Under X.org (not wayland)

Perhaps there is just a X.org bug, or it is due to 3.18 version.

**Comment by gnunn1** [comment] 2016-05-02 13:32
Thanks for the quick reply. I'm using Xorg as well, personally I'd suspect GTK. If it's due to the older version, I may have to disable this feature in versions older then 3.20 as I'm not sure things like the painting around the drop down menu are correctable by me.

**Comment by Boiethios** [comment] 2016-05-02 13:35
Oh you can just do nothing, there is not a troublesome bug. I thought it could be fixed, that is just why I reported it.

**Comment by arshavindn** [comment] 2016-05-02 13:47
I can confirm this. It happens on the unfocused pane, then focus back on them the shadows were gone.

**Comment by gnunn1** [comment] 2016-05-02 13:54
@arshavindn Are you also on GTK 3.18?

**Comment by egmontkob** [comment] 2016-05-02 14:01
Same here. Ubuntu Xenial (X11, GTK 3.18.9, etc.)

**Comment by gnunn1** [comment] 2016-05-02 14:07
@Boiethios One other un-related question, are you using Adwaita as the theme as you don't seem to be getting the new style scrollbar I added and that one I did test under 3.18 but maybe I need to re-visit it.

**Comment by Boiethios** [comment] 2016-05-02 14:46
@gnunn1 Yes, I use Adwaita theme.

**Comment by arshavindn** [comment] 2016-05-02 15:24
@gnunn1 yes, Ubuntu Gnome 16.04, gtk 3.18

**Comment by gnunn1** [comment] 2016-05-03 03:07
So I played around with it a bit tonight, seems to be an issue with GTK restricting the drawing to a region rather then drawing the whole widget as per the documentation for queue_draw. This is why the area around the context menu is drawn un-dimmed, it's actually part of the draw region so gets drawn correctly.

I've tried a few different things to force a draw of the whole region but not much luck so far, calling queue_draw on the top level window fixes the context menu but not the other issues. I'l try to ping the GTK IRC channel tomorrow during working hours and see if anyone has an idea.

**Comment by egmontkob** [comment] 2016-05-03 04:41
Should invoking the menu of a non-focused widget give the focus to that widget?

So far I believed the buggy part was the immediate area around the menubar. Now it seems to me it's the other way around: that one is the correct, the bug is that the rest is not repainted. Am I right?

You might trigger a repaint of the entire vte widget by re-installing the bg/fg color or the entire palette, or toggling the allow_bold setting back and forth etc. (even though, strictly speaking it's not documented that e.g. when altering the default background color even the cells with nondefault background are repainted, as well as that there's no shortcut to catch if it's changed to the same value (I'm not even sure about it :)).) Does this by any chance provide a sufficient workaround?

**Comment by egmontkob** [comment] 2016-05-03 04:58
Note: vte does a full repaint on focus in/out. No clue why (maybe to get rid of display glitches, should there be any), and no clue if it's explicitly done by vte or is standard gtk behavior.

When opening the menu, the bug I believe occurs due to the lack of this full repaint, since gtk's notion of the focused widget diverges from terminix's notion of the focused (active) terminal (and that's fine).

**Comment by gnunn1** [comment] 2016-05-03 13:16
@egmontkob Thanks for the suggestions, I tried toggling the allow bold flag with no effect. I really think the problem has to do with the popover and the way GTK is managing the drawing of it. Based on what I'm seeing, the issue is that when GTK 3.18 redraws the VTE widget it's restricting the draw region to just the popover rather then the whole widget like in 3.20. I've searched the GTK bug list but didn't see any recently fixed bugs that were obvious candidates for this behavior.

As mentioned above, I've tried using queue_draw on the top level window, it gives better results but not consistently.

As to whether changing the "terminix" focus when dropping down the menu is the right thing to do, I opted for this behavior because the previously focused terminal loses focus and thus draws dim when the unfocused menu is pressed, if I don't make the terminal with the menu focused everything is dim which just seems weird. I would think working around this would get a bit convoluted. Also, highlighting the terminal the menu is working against seems like the right thing to do.

**Comment by gnunn1** [comment] 2016-05-03 13:44
I asked on the gtk+ IRC about this, basically it sounds like they removed clipping when drawing from 3.20 hence why it works there and not on 3.18. As far as I can see, here are the options:

* Status quo and do nothing. Not really an option, not into shipping features that sort of work
* Soft disable the feature for GTK 3.18. This would remove the dim options from the preferences and profiles dialog but if someone really wanted to they could still set it in dconf
* Hard disable. Remove the options and prevent the drawing from happening in 3.18 and earlier
* Re-do the feature using font dimming a-la terminator

Of these options, I'm leaning towards soft-disabling, any thoughts?

**Comment by egmontkob** [comment] 2016-05-04 10:28
I'd give it another try to see if re-installing the palette at the right moment (after terminator's notion of the focused terminal changes, but before the menu is presented) fixes it... I really think it should fix it... ;)

**Comment by gnunn1** [comment] 2016-05-04 13:08
@egmontkob Changing the VTE colors, including the palette, doesn't seem to trigger a redraw presumably because VTE knows the colors haven't changed? If you want to play around with it I'd appreciate it, maybe a second pair of eyes would see something I am missing.

The queueDraw for focus changes happens in the methods ```onTerminalWidgetFocusIn``` and ```onTerminalWidgetFocusOut```. To trigger the color change, I replaced the vte.queueDraw() line with ```applyPreference(SETTINGS_PROFILE_PALETTE_COLOR_KEY);``` to have terminix re-apply the palette color (plus the other colors as well, it's al part of the same block).

**Comment by gnunn1** [comment] 2016-05-04 13:10
Hang on a second, I think I'm an idiot and missed something obvious...

**Comment by gnunn1** [comment] 2016-05-04 13:26
This should be fixed now, I was having a mental block and was focused on the terminal focus in and out and somehow thinking the menu was triggering them, mostly because I tied in the search field to them as well and mentally I expanded that to all widgets.

It was easily fixed by adding map/unmap event handlers to the popover to redraw vte if dimUnfocused is active.

**Comment by Boiethios** [comment] 2016-05-04 13:43
Have you push something ? It is worse now.

**Comment by gnunn1** [comment] 2016-05-04 13:48
Yes, I pushed a change to terminal.d that redraws the VTE when the popover is shown/hidden. It's working fine for me here on Ubuntu 16.04 whereas before it was not. I just double-checked my commit to make sure I didn't check in something inadvertently but didn't notice anything.

@egmontkob Can you let me know if this fix is working for you or not just as another data point.

**Comment by gnunn1** [comment] 2016-05-04 14:31
I just tested it on Fedora 23 as well, seems to fix the problem there as well as far as I can tell.

**Comment by Boiethios** [comment] 2016-05-04 14:54
I checked again, I have more visual issues with the last version.

**Comment by egmontkob** [comment] 2016-05-04 15:18
Works fine for me :)

A really minor nit: When closing the menu, there's a short but noticeable time (maybe a quarter of a second) when two terminals are non-dimmed (both the active and whose menu was opened). Probably not worth it trying to address.

Just wondering: How much would it make your life easier if vte implemented https://bugzilla.gnome.org/show_bug.cgi?id=758368 ?

**Comment by gnunn1** [comment] 2016-05-04 15:47
@egmontkob Thanks for testing, the delay might be because I connected the map/unmap signal using the AFTER flag, looking at the docs this probably isn't necessary. I'll test it out tonite and remove it if not needed.

I'm not sure that implementing this in VTE is a good idea, at least for Terminix, because a terminal is considered focused in a variety of use cases outside of just the vte widget being focused. For example, if the search widget is focused I consider the terminal focused and don't dim it, this wouldn't work for a VTE enabled feature unless an event is provided to allow the app to decide what the state is. Same for the menu button and the context menu.

**Comment by gnunn1** [comment] 2016-05-04 15:47
@Boiethios Dumb question, any chance the app is not being built correctly when you are trying this?

**Comment by egmontkob** [comment] 2016-05-04 16:08
@gnunn1 I definitely wouldn't auto-connect it to the focused state. I'd let the caller app decide when to install a color mapper that dims the colors, and when to remove the mapper. From your point of view, this would result in pretty much the same design as Terminator's when it installs a new color palette, except that it'd also work for RGB colors.

**Comment by gnunn1** [comment] 2016-05-04 16:19
@egmontkob Thanks for the clarification, that makes sense. It would make my life easier and from an architecture perspective is the right direction to go IMHO. If you look at what Terminix needs to make this work:

a. Add a draw handler to apply the effect as a post-processing step 
b. Litter the code with queue_draw calls to make sure the post-processing kicks-in at the right times

From my perspective having the VTE handle it is a much cleaner approach. Also, I believe it would be much easier to get the optimum visual effect for this if it was handled during the draw operation instead of as a post-processing step.

**Comment by gnunn1** [comment] 2016-05-05 00:44
@egmontkob I removed the AFTER from the map/unmap signals, give it a try and see if it helps the delay at all though I'm not overly optimistic.

**Comment by egmontkob** [comment] 2016-05-05 05:08
@gnunn1 No change; nevermind! ;)

**Comment by Boiethios** [comment] 2016-05-05 14:41
@gnunn1 I do not think so, but since the last update, everything works fine for me.

**Comment by gnunn1** [comment] 2016-05-05 14:49
@Boiethios Thanks for the update, weird but glad it's working now.

**Closed by gnunn1** 2016-05-05 14:49 UTC
Labels: bug
