### ISSUE TITLE
Window resizing is very sluggish

### ISSUE THREAD

**Issue by vaijab** [gnunn1/terminix#102] opened 2016-02-23 10:39 UTC
terminix-0.50.2-4.1.x86_64
gnome-shell-3.18.3-1.fc23.x86_64

**Comment by gnunn1** [comment] 2016-02-23 11:25
What video driver are you using?

**Comment by vaijab** [comment] 2016-02-23 11:33
I am using opensource i915, kernel 4.5.0-0.rc4.git2.2.fc24.x86_64. Nothing else is sluggish in my gnome environment, so I suspect that this issue is terminix specific.

**Comment by gnunn1** [comment] 2016-02-23 14:52
I'm not able to reproduce, I'm also using the i915 driver but kernel 4.4.1-2. Is the sluggish behavior the same whether you have a simple layout with one terminal versus many terminals? I assume gnome-terminal does not exihibit this behavior?

Also, one thing to try is to disable the transparency option in dconf-editor. It's under /com/gexperts/Terminix/enable-transparency. Note don't just set the transparency slider to 0, the option in dconf-editor disables it at a lower level.

**Comment by vaijab** [comment] 2016-02-23 15:20
It could be that it's the version of kernel which is causing it. I am using Skylake CPU. I will try a different kernel (4.4.x).

**Comment by gnunn1** [comment] 2016-02-23 15:24
Also, since you are using Skylake are you using UXA or SNA acceleration with the Intel driver? For broadwell and skylake SNA was buggy so maybe you switched to UXA, I know I flipped back and forth between the two on my Broadwell laptop before getting SNA stabilized. I find UXA sluggish for everything on my machine but maybe terminix is particularly bad with it in your case.

If you haven't explicitly configured UXA then you should be on SNA.

**Comment by vaijab** [comment] 2016-02-23 15:32
@gnunn1 I am not sure how to check? Would you happen to know how to check in which mode I am running?

**Comment by phw** [comment] 2016-02-23 15:56
> @gnunn1 I am not sure how to check? Would you happen to know how to check in which mode I am running?

There should be something in your X.org logs. On a systemd based distro journalctl should contain something, e.g. on my system with SNA enabled the result for `journalctl -b | grep SNA` is:

```
Feb 23 10:49:32 zoidberg /usr/lib/gdm/gdm-x-session[1025]: (II) intel(0): SNA compiled from 2.99.917-552-ge41040f
Feb 23 10:49:32 zoidberg /usr/lib/gdm/gdm-x-session[1025]: (II) intel(0): SNA initialized with Ivybridge (gen7, gt2) 
```

**Comment by vaijab** [comment] 2016-02-23 21:11
Looks like SNA. I tried switching to UXA, but gdm won't start. I will keep digging whenever I get some time. Thanks for your help, @gnunn1 .

**Comment by gnunn1** [comment] 2016-02-23 21:13
Thanks, did you try disabling the transparency like I suggested?

**Comment by vaijab** [comment] 2016-02-23 21:15
Yes, I did, but that didn't help.

**Comment by egmontkob** [comment] 2016-03-15 05:54
Probably irrelevant, but worth noting here for future reference:

VTE rewraps the contents upon resize as a synchronous operation, blocking for its duration which is roughly proportional to the scrollback size (the number of lines actually used, not the one configured in prefs). On my machine it's approx 0.2 seconds per 1M lines of scrollback. Multiply it by the number of widgets that are being resized at once, of course.

So, if rewrapping is enabled and a large scrollback buffer is chosen, resizing is expected to be sluggish. The workaround is to either disable rewrapping or set a smaller scrollback buffer (e.g. 100.000 lines is probably big enough for practical purposes, yet rewraps almost instantaneously).

When this is hit, however, it's obviously not Xorg but Terminix itself that'd consume 100% CPU time.

**Comment by gnunn1** [comment] 2016-03-21 13:14
I'm going to close this as I can't reproduce it and no one else is complaining about it.

**Closed by gnunn1** 2016-03-21 13:14 UTC
Labels: bug, Can't Reproduce

**Comment by alexwhitman** [comment] 2016-04-09 12:56
> I can't reproduce it and no one else is complaining about it.

I can reproduce with the nouveau open source driver.  Gnome Terminal resizes quickly but Terminix resizes in "jumps".  Not an issue for me as I tend to run maximised, but thought I'd mention it.

**Comment by jamiesonbecker** [comment] 2018-12-08 16:48
I see this as well, although it might be a slightly different problem or cause: it's mostly a problem when a window is maximized and I drag it down from the upper right corner. XFWM4, Nvidia binary drivers on GTX 1050, Debian Stretch, no customization, . Tilix tries to jump and resize back up to maximized until I get it far enough away, so it flashes back and forth, trying to resize to maximized.

The following XFCE options don't seem to have any effect:

1. disabling display compositing
2. automatic tiling when moving toward screen edge
3. use edge resistance instead of window snapping
4. minimum size of windows to tragger smart placement

*However*, under **Appearance** in Tilix **Preferences**, changing window style inside tilix to anything other than **Normal** (and restarting tilix) does resolve the problem. (Chrome custom title bars don't exhibit this problem, so it seems to be specific to the Tilix custom title bar.)
