### ISSUE TITLE
Can't send file to Hosted Weblate

### ISSUE THREAD

**Issue by psokol** [gnunn1/terminix#795] opened 2017-02-23 09:36 UTC
I can't upload updated polish language file to Hosted Weblate. Every attempt returns "get() returned more than one Unit -- it returned 2!" error message.
[terminix.zip](https://github.com/gnunn1/terminix/files/796065/terminix.zip)

**Comment by phw** [comment] 2017-02-23 09:52
Can you upload the file here or open a pull request? Probably something wrong with the file itself.

**Comment by psokol** [comment] 2017-02-23 13:50
The file is attached to first comment.

**Comment by phw** [comment] 2017-02-23 14:18
Thanks, missed that somehow. 

I reported this issue to https://github.com/WeblateOrg/weblate/issues/1381 , but also opened a pull request here with you updated translation. Hopefully Weblate will import it then.

I can reproduce with other files, see my comment on the Weblate issue.

**Comment by psokol** [comment] 2017-02-26 20:57
Thanks, hopefully they'll fix this soon.

**Comment by phw** [comment] 2017-02-27 09:16
This is now a confirmed bug in Weblate and targeted for the next release. Since the development there is pretty active and the hosted weblate Terminix uses is always using latest code I expect this to be fixed soon.

In any way, this is not Terminix specific and importing the translation has already been dealt with, so I think we should close this issue.

**Comment by phw** [comment] 2017-02-27 12:12
Fixed on Weblate

**Comment by gnunn1** [comment] 2017-02-27 12:31
Thanks for taking care of this @phw

**Closed by gnunn1** 2017-02-27 12:31 UTC
Labels: Upstream
