### ISSUE TITLE
[Bookmarks] Bookmarks don't get saved

### ISSUE THREAD

**Issue by phw** [gnunn1/terminix#769] opened 2017-02-15 09:11 UTC
For me bookmarks don't get saved at all. If I add bookmarks they are visible, I can also use them. But once I completely close Terminix and open it again it is all gone. I also can't see anything bookmark related in gconf.

**Comment by phw** [comment] 2017-02-15 09:26
Ok, this is a bit strange. It works if I compile Teriminix from Git with dub and run it locally from the Git directory. But I have also installed terminix-git from the AUR system wide (just updated it, so it is usig same git revision as my local test).

Behavior is the following (always assuming Terminix is completely closed before opening it):

- Running Terminix locally from inside the git repository (fresh build with dub) works. I can create bookmarks, and they are preserved when closing and restarting terminix
- Running the globally installed terminix from terminix-git does load the saved bookmarks, but all bookmarks I create from inside this build are lost when restarting terminix

There are of course differences in how Terminix is build (dub vs autotools), probably related to this. 

@dsboger Any idea what could be happening?

**Comment by phw** [comment] 2017-02-15 09:51
New results: 

The terminix-git version compiled with ldmd crashes with a core dump when closing if I have also edited bookmarks in this session. Compiled with traces enabled, here is a trace of me starting terminix, opening session, adding a bookmark folder, closing settings and then closing the terminal:

https://gist.github.com/phw/e241a2d6effe7fd9668fb21debfd45f9

I also tried to compile with ldmd `-debug` instead of `-release`, but I cannot even run that build, it crashes directly with:

```
Fatal Error while loading '/usr/lib/libphobos2-ldc.so.70':
	The module 'std.regex.internal.parser' is already defined in 'terminix'.
```

**Comment by gnunn1** [comment] 2017-02-15 14:13
The issue with LDC and the ```std.regex.internal.parser``` error should be addressed by this line in dub.json:

```
"dflags-ldc": ["-disable-linker-strip-dead"]
```
I think terminix-git uses the autotools which should be doing the same thing, however if you want to try compiling with dub with ldc do this:

```
dub --build=debug --config=trace --compiler=ldc2
```

**Comment by gnunn1** [comment] 2017-02-15 23:28
Note that bookmarks are saved to ```~/.config/terminix/bookmarks.json```

**Comment by gnunn1** [comment] 2017-02-15 23:33
I also realized I wasn't creating the path if it doesn't exist, I've checked in a change to do that so maybe this will fix it.

**Comment by phw** [comment] 2017-02-16 08:09
No, it is not the path, since the path and file exist and also get loaded.

I tested again with dub and building with ldc2, terminix crashes in this case when serializing the bookmarks. I ran it with gdb and backtrace, see output at https://gist.github.com/phw/b07e130073dac3def9dff13f4af4ee6e

**Comment by dsboger** [comment] 2017-02-16 14:03
I'm having the same issue with the `terminix-git` from AUR. No `bookmarks.json` flie is created, but the `~/.config/terminix` folder is. I'll try a build with dmd to see if anything changes.

**Comment by dsboger** [comment] 2017-02-16 14:24
I rebuilt `gtkd` and `terminix-git` with `dmd` and bookmark saving works. Maybe it is a bug in the standard libraries of ldc or the compiler itself.

**Comment by gnunn1** [comment] 2017-02-16 14:38
@phw That stack trace looks like some sort of recursion is going on unless you really have folders nested that deep. I suspect LDC is doing something funky, I'll investigate.

**Comment by phw** [comment] 2017-02-16 16:04
Nope, no deep nesting, actually a single folder with entries below. But the gdb backtrack would go on and on if I select to show more. So definitely looks like some endless recursion happening.

**Comment by gnunn1** [comment] 2017-02-16 21:50
@phw I'm not able to reproduce with ldc2, it seems to be working fine for me with bookmarks saving as expected. Are you using dub to build with ldc2 as per the command line I posted? here's my LDC2 version:

```
LDC - the LLVM D compiler (1.1.0):
  based on DMD v2.071.2 and LLVM 3.9.1
  built with LDC - the LLVM D compiler (1.1.0)
  Default target: x86_64-unknown-linux-gnu
  Host CPU: haswell
  http://dlang.org - http://wiki.dlang.org/LDC

  Registered Targets:
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```

**Comment by phw** [comment] 2017-02-17 00:23
Yes, tried with both autotools via the terminix-git AUR package and via dub. If I compile it with ldc2 I get that crash when saving bookmarks. Using DMD gives a working build.

I can check tomorrow what version of ldc this is I have installed, but it should be whatever Arch currently has available.

**Comment by gnunn1** [comment] 2017-02-17 02:06
I have a newer version of LDC installed then Arch, I can reproduce the issue with the older version (1.0.0) instead of my version (1.1.0).

**Closed** 2017-02-17 02:39 UTC
Labels: bug

**Comment by gnunn1** [comment] 2017-02-17 02:41
I've worked around it with an ugly hack, code was failing on each bookmark calling ```super.serialize(parent)```. Copying this code from the super method and placing it inline fixes the issue. I'll have to try to remember to go back and revert this once LDC 1.1 is prevalent.

**Comment by luigimassa** [comment] 2017-08-23 08:26
Hi guys, 
I installed tilix in ubuntu 17.04 
But I've problems to save bbokmark

I create a bookmark but when I kill tilix or exit from sessions, bookmarks are no more present in tilix

Can you help me please?
Thanks

**Comment by gnunn1** [comment] 2017-08-23 12:07
@luigimassa Bookmarks are saved in ```~/.config/tilix/bookmarks.json```, do you see a file there? Also, when you say kill tilix I assume you mean it close it normally and not something like ```kill 9```?

**Comment by luigimassa** [comment] 2017-08-23 16:21
Hi 
thanks to answer me.

The file `~/.config/tilix/bookmarks.json`  don't exist.
I tried to kill tilix to try serch the bug, but tilinx don't generate the file also when I close normally the session of ubuntu or when I shutdown the pc
thanks in advance

**Comment by gnunn1** [comment] 2017-08-23 20:39
If you run tilix in gnome-terminal, i.e. ```tilix``` without any other instances of tilix running, create a bookmark and then exit are any errors or warnings output to the console?

**Comment by gnunn1** [comment] 2017-08-23 20:40
Also, can you confirm that the folder ```~/.config/tilix/``` exists?

**Comment by luigimassa** [comment] 2017-08-24 06:47
Hi, 
I tried your suggestions and I found the problem.

 - delete your file ~/.config/tilix/bookmarks.json
 - kill tilix
 - open tilix in quake mode
 - add a bookmarks
 - exite from quake mode
 - kill tilix
 - open tilix in quake mode => there aren't  bookmarks and file bookmarks.json wasn't  created

Now
 - open tilix not in quake mode
 - add bookmark
 - close tilix
 - kill tilix
 - open tilix in quake mode
 - add bookmark
 - exit from quake mode
 - kill tilix
 - open tilix in quake mode, you see all bookmarks.

**Comment by luigimassa** [comment] 2017-08-24 06:55
ops....  
now I have this problem  when I add a bookmark
`(tilix:12700): Gtk-CRITICAL **: gtk_file_chooser_select_filename: assertion 'filename != NULL' failed`

the file `./config/tilix/bookmarks.json` exist

**Comment by gnunn1** [comment] 2017-08-24 13:33
O'm confused by your steps to reproduce, when you say ```kill tilix``` after ```close tilix``` what exactly are you doing when you kill tilix? Are you existing the terminal by typing ```exit```. If I remember correctly bookmarks get saved when you exit tilix so if you are killing the process that might be causing your issue.

**Comment by gnunn1** [comment] 2017-08-24 13:34
BTW I tested this locally and it seems to be working fine for me when I exit Tilix by typing ```exit``` with only a single terminal open.

**Comment by cgerada** [comment] 2019-09-16 14:53
i know this is an old thread, but has anyone solved this,  my bookmarks are not being saved
and I do not have a ~/.config/terminix [tilux] /bookmarks.json file on my system , (adding bookmarks does not create this file) when I quit tilix all the bookmarks that I created dissapear, Any idea ?

**Comment by verajosemanuel** [comment] 2019-11-20 13:37
same here. Bookmarks are not saved on Ubuntu Eoan

**Comment by koshyviv** [comment] 2020-05-04 13:22
Is this resolved?

I installed this afresh today - and just saw all the bookmarks i created are no longer there.
I do not have the folder present - `~/.config/tilix/bookmarks.json
`
Thanks

**Comment by m-usai-almaviva** [comment] 2020-05-27 09:37
Please reopen the issue, my bookmarks don't get saved too.
I'm using Tilix in Ubuntu Budgie 20.04

**Comment by pvanhemmen** [comment] 2020-06-25 08:48
I can confirm issues with bookmarks not being saved in Ubuntu Focal Fossa 20.04. The bookmarks.json file is there and initital settings have been written to it, but all changes i try to make in the bookmark settings menu are discarded and not being written to disk.

**Comment by hluaces** [comment] 2021-01-28 22:08
I can reproduce the issue.

Bookmarks are not being saved to disk and the file `~/.config/tilix/bookmarks.json` does not exist (the directory does).

Creating an empty `bookmarks.json` causes Tilix to be unable to start up:

```
$ tilix
2021-01-28T22:25:24.926 [error] manager.d:615:load No se pudieron cargar los marcadores debido a un error inesperado
2021-01-28T22:25:24.926 [error] manager.d:616:load std.json.JSONException@std/json.d(308): JSONValue is not an object
----------------
??:? pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x7f19e66b1984]
??:? inout pure ref @safe inout(std.json.JSONValue) std.json.JSONValue.opIndex(immutable(char)[]) [0x7f19e6709ebf]
??:? [0x557c1bb3166f]
??:? [0x557c1bb33aec]
??:? [0x557c1bb1f783]
??:? g_closure_invoke [0x7f19e5cbb800]
??:? [0x7f19e5ccf812]
??:? g_signal_emit_valist [0x7f19e5cdab9c]
??:? g_signal_emit [0x7f19e5cdb0d1]
??:? g_application_register [0x7f19e5de97e0]
??:? [0x7f19e5de9bbc]
??:? g_application_run [0x7f19e5de9f40]
??:? [0x557c1ba3e392]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f19e64259da]
??:? _d_run_main2 [0x7f19e64257ed]
??:? _d_run_main [0x7f19e642565c]
??:? __libc_start_main [0x7f19e617d0b1]
??:? [0x557c1ba3a3cc]
Violación de segmento (`core' generado)
```
I've tried to add the value `{}` to the file, but the problem still stands.

I'm using Ubuntu 20.04 and the following tilix version:

```
Versiones
	Versión de Tilix: 1.9.1
	Versión de VTE: 0.60
	Versión de GTK: 32420

Características especiales de Tilix
	Notificaciones activadas: 0
	Disparadores activados=0
	Insignias activadas=1
```

**Comment by sallec** [comment] 2022-02-04 17:22
I had problem with unsaved bookmark after computer restart. I have create several bookmarks and I was using them. Then I restarted my computer and no bookmarks were saved!
Folder tilix and file bookmarks.json did not exist at location ~/.config/tilix/bookmarks.json

After some testing I realized that bookmarks are saved not when they are created but when you exit tilix!
Probably when I restarted computer system killed tilix and bookmarks were not saved.

Solution would be to save bookmark as soon as it is created (not to keep it in memory and wait for clean exit from application).

Can you please fix this?

**Comment by kenarp** [comment] 2023-03-09 05:49
> 

Got the same problem on Arch Linux. Did you happen to get a solution?

**Comment by esturniolo** [comment] 2024-03-25 09:22
Same here with Ubuntu 22.04
Tilix version
```
Versions
	Tilix version: 1.9.4
	VTE version: 0.68
	GTK Version: 3.24.33
```

This feature is amazing. The only problem is that doesn't work :(
