### ISSUE TITLE
Segmentation fault when adding a custom link

### ISSUE THREAD

**Issue by edubxb** [gnunn1/terminix#664] opened 2016-12-31 14:46 UTC
Edit profile > Advanced > Custom Links > Edit > Add > Enter regex `*.py` + Intro > Segmentation fault

```
$ terminix --version
Versions
	Terminix version: 1.4.2
	VTE version: 0.46
	GTK Version: 3.22.5

Terminix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

**Comment by gnunn1** [comment] 2016-12-31 15:43
It's being caused by ```*.py``` being an invalid regex and my code doesn't handle it properly. I've committed a change that stops it from crashing and displays a warning (see below). However, this needs some further work as it shouldn't allow the apply button to be active with invalid regex's present as it will just propagate the error upstream.

I'll fix this later today.

![screenshot from 2016-12-31 10-40-03](https://cloud.githubusercontent.com/assets/9358238/21578226/042c1fee-cf46-11e6-89b3-735b17e362a3.png)

**Closed** 2016-12-31 17:36 UTC
Labels: bug

**Comment by gnunn1** [comment] 2016-12-31 17:37
I've re-worked the Custom Links and Trigger dialogs and this should be fixed now, errors appear as per example below. I've also updated the terminal code to catch this exception in case someone edits a preference directly in dconf.

![screenshot from 2016-12-31 12-35-19](https://cloud.githubusercontent.com/assets/9358238/21578632/d2d8e232-cf55-11e6-9413-9861da61e0ed.png)
