### ISSUE TITLE
If app started in Quake mode with height at 100% - window doesn't react to height option change.

### ISSUE THREAD

**Issue by Anton-Latukha** [gnunn1/terminix#573] opened 2016-11-12 01:52 UTC
At first. Thank you for the alignment. Now it is perfect for me.

Discovered a bug.
Must be simple to reproduce.

Using current GIT version (on Arch, KDE Plasma)

_Conditions:_
Using Quake mode, using any alignment, for exemple:
![1](https://cloud.githubusercontent.com/assets/20933385/20234619/2d07acca-a887-11e6-8c23-8d42ff1ba1ae.png)

_Syndrome:_

But trying to change height:
![2](https://cloud.githubusercontent.com/assets/20933385/20234868/00d7edc2-a88c-11e6-8178-3fcad7d475e7.png)

Results into nothing. So user can decide: "That option is not working".

But, if select height not at maximum (like above) and reopen Terminix:
![3](https://cloud.githubusercontent.com/assets/20933385/20234624/30991d1a-a887-11e6-8aec-888d3657cf1b.png)
Option works.

And from this position you can change height as you want and it works. Also setting it to maximum, and backwards (while Terminix running).

_Short sum description:_
But set height to maximum and reopen application. - Option doesn't work again (like second picture).

So, seems dynamic redrawing of window not working when application started with height set to 100%.
Like it locked somewhere.

P.S.
Maybe it is DE sticking windows to screen borders (here I have default settings).

**Comment by gnunn1** [comment] 2016-11-12 14:36
I can't reproduce this using Gnome, might be be an issue specific to KDE. Do you have a different DE on your system that you could try it with to confirm it's KDE and not something else specific to your system?

**Comment by gnunn1** [comment] 2016-11-16 17:49
No reply for OP and KDE isn't a DE that is officially supported, closing issue.

**Closed by gnunn1** 2016-11-16 17:49 UTC
Labels: bug, Can't Reproduce
