### ISSUE TITLE
Automatically Crashed when Building app using " npm i "

### ISSUE THREAD

**Issue by udara-u3** [gnunn1/terminix#89] opened 2016-02-20 19:25 UTC
Terminix was automatically crashed when I building app using `npm i` command. I have tried 2 or three times it was the same. When the middle of building app Terminix is suddenly diapering.
Ubuntu Xenial with elementary Loki.

**Comment by gnunn1** [comment] 2016-02-20 23:38
Is this with an open source app that I could download and try to reproduce? Also, does this work in Gnome Terminal?

**Comment by alex285** [comment] 2016-02-20 23:55
I'm using node on Terminix all the time. Never seen this :/

**Comment by alex285** [comment] 2016-02-21 00:03
@gnunn1 to test you can just make a package file

mkdir test
cd test
touch package.json

add some packages on json file

{
  "name": "test",  
  "version": "0.0.1",
  "devDependencies": {
    "babel": "6.3.26",	
    "node-gyp": "3.2.1"
	}
}

then run "npm i"
Assuming you have node installed

**Comment by gnunn1** [comment] 2016-02-21 00:39
Thanks Alex, I was thinking maybe there is something specific about his build (specific sequence of chars emitted, etc) that might be causing the issue. I suspect this would be a VTE issue rather then Terminix since my code isn't involved at that point generally speaking, but I always like to rule myself out first.

**Comment by udara-u3** [comment] 2016-02-21 04:31
Yes It's open source app, and It's working with Gnome terminal and Pantheon Terminal too.
[https://github.com/shockone/black-screen](url) This is the app.. Thanks.

**Comment by alex285** [comment] 2016-02-21 11:11
@udara-u3 I have built and run black-screen with Terminix numerous times. No crashes.

**Comment by udara-u3** [comment] 2016-02-21 11:14
@alex285 Maybe it's with OS, I'm using Ubuntu Xenial with Elementary Daily build ( Loki ).
So as I know you're using Fedora Rawhide correct ?

**Comment by gnunn1** [comment] 2016-02-21 14:33
Like Alex I can't reproduce it. Can you try to run a debug version of terminix under gdb:

1. Download a debug version of terminix here http://www.gexperts.com/files/terminix_debug.zip
2. Run this debug version in gdb, ```gdb ./terminix```
3. You will be dropped into the gdb prompt, type ```run``` and enter
4. Terminix will start, do your build and get it to crash
5. Go to the GDB prompt and get a backtrace by type ```bt```
6. Copy and paste the backtrace into this issue

**Comment by udara-u3** [comment] 2016-02-21 14:36
Aha ok I'll try. :)

**Comment by phw** [comment] 2016-02-24 10:22
I wonder whether `npm -i` is just a red herring and the crash itself is unrelated to the execution of this command. Maybe something similar to what we experience in #101.

@udara-u3 A backtrace would really help to narrow this down

**Comment by gnunn1** [comment] 2016-02-29 23:10
@udara-u3 Any updated on this, otherwise I'm closing this issue as I cannot reproduce and need your assistance.

**Comment by gnunn1** [comment] 2016-03-02 01:57
Closing, no response from OP and I think it's likely a duplicate of #101

**Closed** 2016-03-02 01:57 UTC
Labels: bug, Can't Reproduce
