### ISSUE TITLE
[Wayland] Quake height not satisfied

### ISSUE THREAD

**Issue by Jiehong** [gnunn1/terminix#691] opened 2017-01-14 08:39 UTC
Tested on Gnome 3.22, on wayland session on Archlinux.

When running `terminix --quake`, the screen that appears defaults to full-size, even if the height in the parameter is set to something else.
Yet, after opening the quake mode, and going into preferences, moving the height cursor a bit resizes the window correctly.

I also noted that the window appears from the bottom-right corner, and the animation is chopped, but when launching terminix normally, the opening animation is from the centre of the screen, and is not chopped.

**Comment by gnunn1** [comment] 2017-01-14 14:38
Are you using terminix 1.4.2 or the version from the terminix-git package? With the git version it's working fine for me on Arch, Wayland and Gnome 3.22 but I honestly can't think of any reason why 1.4.2 shouldn't work as well.

Having said that, note that Wayland is a mess when it comes to things like quake windows because of the limitations it places on allowing applications to position themselves on the screen.

In the worse case, you can force Terminix to use the X11 backend on Wayland:

```
export GDK_BACKEND=x11; terminix --quake
```

**Comment by Jiehong** [comment] 2017-01-14 14:45
I'm using terminix 1.4.2.

This issue happens on my laptop screen, but if I plug an external screen, then terminix's window's height is correct (but its position is in the middle of the screen, not on top…).

I'll give a try to the x11 backend then I guess

**Comment by Jiehong** [comment] 2017-01-15 08:59
Trying with `export GDK_BACKEND=x11; terminix --quake` does not fix the issue actually.

Is there a way to have terminix output some logs somehow?

**Comment by gnunn1** [comment] 2017-01-15 14:43
You have to compile terminix to get logging, it's not included in release builds. To compile it with logging, the command would be:

```
dub build --build=debug --config=trace
```

Of course you need a D compiler and dub installed on your system.

Also, can you you take a screenshot of the dconf-editor showing the quake parameters that are set, for example:

![screenshot from 2017-01-15 09-40-55](https://cloud.githubusercontent.com/assets/9358238/21963330/f7b47334-db06-11e6-8364-4d9275419406.png)

Also, if you switch to X11 at the login screen, does everything work as expected?

**Comment by gnunn1** [comment] 2017-01-19 05:22
@Jiehong Have you had a chance to try to build terminix with tracing?

**Comment by Jiehong** [comment] 2017-01-19 19:39
@gnunn1 I was pretty busy those past few days, sorry.

However, I just compiled terminix, and tried to launch it, but it doesn't want to launch at all for now:

```
./terminix --quake
2017-01-19T19:36:40.403:app.d:main:36 CWD = /home/jiehong/Dev/terminix
2017-01-19T19:36:40.403:app.d:main:40 PWD = /home/jiehong/Dev/terminix
2017-01-19T19:36:40.403:app.d:main:51 UHD = /home/jiehong
2017-01-19T19:36:40.435:app.d:main:74 Starting terminix with 2 arguments...
2017-01-19T19:36:40.435:app.d:main:76 arg[0] = ./terminix
2017-01-19T19:36:40.435:app.d:main:76 arg[1] = --quake
2017-01-19T19:36:40.435:app.d:main:98 No terminix UUID found
2017-01-19T19:36:40.435:app.d:main:113 Creating app
2017-01-19T19:36:40.436:app.d:main:117 Running application...
2017-01-19T19:36:40.436:application.d:onAppStartup:482 Startup App Signal
2017-01-19T19:36:40.436:resource.d:findResource:43 looking for resource /usr/local/share/terminix/resources/terminix.gresource
2017-01-19T19:36:40.437:resource.d:findResource:43 looking for resource /usr/share/terminix/resources/terminix.gresource
2017-01-19T19:36:40.437:resource.d:findResource:47 Resource found and registered /usr/share/terminix/resources/terminix.gresource
2017-01-19T19:36:40.437:application.d:loadResources:151 No specific CSS found /com/gexperts/Terminix/css/terminix.Adwaita.css
2017-01-19T19:36:40.438:application.d:onAppStartup:486 Monitoring shortcuts
2017-01-19T19:36:40.457:application.d:applyPreference:545 Default menu accelerator is F10
2017-01-19T19:36:40.457:application.d:onCommandLine:361 App processing command line
2017-01-19T19:36:40.457:cmdparams.d:this:212 Command line parameters:
2017-01-19T19:36:40.457:cmdparams.d:this:213 	working-directory=
2017-01-19T19:36:40.457:cmdparams.d:this:214 ["\tsession="]
2017-01-19T19:36:40.457:cmdparams.d:this:215 	profile=
2017-01-19T19:36:40.457:cmdparams.d:this:216 	title=
2017-01-19T19:36:40.457:cmdparams.d:this:217 	action=
2017-01-19T19:36:40.457:cmdparams.d:this:218 	command=
2017-01-19T19:36:40.458:cmdparams.d:this:219 	cwd=/home/jiehong/Dev/terminix
2017-01-19T19:36:40.458:cmdparams.d:this:220 	pwd=/home/jiehong/Dev/terminix
2017-01-19T19:36:40.458:application.d:onCommandLine:386 Activating app
2017-01-19T19:36:40.458:application.d:onAppActivate:457 Activate App Signal
2017-01-19T19:36:40.458:appwindow.d:getQuakePosition:1182 Quake window: monitor=0, x=0, y=0, width=1440, height=549
2017-01-19T19:36:40.459:appwindow.d:moveAndSizeQuake:1114 Actually move/resize quake window

(terminix:5221): GLib-GIO-ERROR **: Settings schema 'com.gexperts.Terminix.Settings' does not contain a key named 'window-style'
```

Is there a new option called `window-style` to add compared to the last delivery? What value should I add to it? (I compiled on 53972fb83abb).

Also, here is a screenshot of my dconf window as well:
![terminix_options](https://cloud.githubusercontent.com/assets/1061229/22122189/49876846-de87-11e6-9ae3-28d41626cde9.png)

**Comment by Jiehong** [comment] 2017-01-19 19:40
Doesn't matter, launching terminix a second time works.

**Comment by Jiehong** [comment] 2017-01-19 19:47
Well, it doesn't launch at all on wayland though (still this property missing). Here is the log under wayland if you want:

[wayland.txt](https://github.com/gnunn1/terminix/files/717605/wayland.txt)

**Comment by gnunn1** [comment] 2017-01-20 23:20
Sorry for the delay in responding, I was out on the west coast yesterday for work and today was a travel day.

You need to compile the settings schema to fix that issue because the version in git has some new options:

```
sudo cp data/gsettings/com.gexperts.Terminix.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```

The ```install.sh``` script does a complete install as well including compiling the schema and resources required.

If this issue is fixed in git please feel free to close it.

**Comment by Jiehong** [comment] 2017-01-21 16:26
Hi,

So, I was able to reproduce the exact same issue.

I launched `terminix --quake` in both x11 and wayland (gnome), and I logged the output:

[x11.txt](https://github.com/gnunn1/terminix/files/721283/x11.txt)
[wayland.txt](https://github.com/gnunn1/terminix/files/721282/wayland.txt)

The log files clearly indicate a different position/size.

**Comment by gnunn1** [comment] 2017-01-21 22:10
I've checked in a change that logs the monitor geometry, I suspect you are getting different results under Wayland then X11 for this call. 

Also, please try the following, in appwindow.d you will see the following lines of code at line 1146:

```
        //getScreen().getMonitorGeometry(monitor, rect);
        getScreen().getMonitorWorkarea(monitor, rect);
```

Can you try un-commenting the first line and commenting out the second so it looks like this:

```
        getScreen().getMonitorGeometry(monitor, rect);
        //getScreen().getMonitorWorkarea(monitor, rect);
```

Re-build terminix and run it to see if it makes any difference.

**Comment by Jiehong** [comment] 2017-01-22 09:46
I've updated, and re-tested:

[x11_new.txt](https://github.com/gnunn1/terminix/files/721836/x11_new.txt)
[wayland_new.txt](https://github.com/gnunn1/terminix/files/721835/wayland_new.txt)

And then uncommented/commented the given lines:
[x11_new_trace.txt](https://github.com/gnunn1/terminix/files/721840/x11_new_trace.txt)
[wayland_new_trace.txt](https://github.com/gnunn1/terminix/files/721839/wayland_new_trace.txt)

First, there doesn't seem to be any difference between `getMonitorWorkarea()` and `getMonitorGeometry`.

Second, the only interesting bits are that the geometry seems to be different:

```
x11:
Monitor geometry: monitor=0, x=0, y=0, width=1440, height=900
Quake window: monitor=0, x=0, y=0, width=1440, height=549
---
wayland
Monitor geometry: monitor=0, x=0, y=0, width=2880, height=1800
Quake window: monitor=0, x=0, y=0, width=2880, height=1098
```

My monitor resolution is `2880×1800` in _both_ cases. It looks like the monitor values are halved under x11 for some reasons.

My `quake-height-percent` being set to `61` in dconf, so a height of `1098` is correct under Wayland.

**Comment by gnunn1** [comment] 2017-01-22 09:50
Are you using Window scaling in the gnome tweak tool?

**Comment by Jiehong** [comment] 2017-01-22 13:23
Window scaling is set to 1 in the tweak tool.

**Comment by gnunn1** [comment] 2017-01-22 13:31
Is this a laptop screen or monitor? A setting of 1 under Wayland is usually represented as -1 in dconf-editor which means autoscale. I presume things are not sized differently for you between x122and Wayland?

**Comment by Jiehong** [comment] 2017-01-22 14:06
It's a laptop screen.

In dconf, `org.gnome.desktop.interface.scaling-factor` is set to its default value (0), and it says that 0 is auto-scale.

Things aren't scaled differently between x11 and wayland as far as I can see.

But in both cases, the calculated height by terminix is correct, so the height of the window should be correctly set.

Maybe… it is correctly set, but the monitor geometry doesn't take into account the scale factor under wayland like it does under x11, so the height is higher than the hight of the screen?

I can test that, I just need to select a scaling factor that should make the height of terminix small enough in both cases. Let me give it a try!

**Comment by Jiehong** [comment] 2017-01-22 14:12
Well, I'm incorrect. I've just tried with a quake-height-percent of 28, and still the same: works in x11, fullscreen in wayland.

So, I guess `appwindow.d:moveAndSizeQuake` is not working under wayland?

**Comment by gnunn1** [comment] 2017-01-22 15:29
The issue is the scaling factor, I've fixed it locally but I need to look into some issues with my Wayland backend detection as it breaks when flipping between X11 and Wayland (i.e. login in one, logout on the other).

Also, When running mixed DPI monitors quake mode works poorly but I can't do anything about it since Wayland has limited support for the features to make this work well.

**Closed** 2017-01-22 15:43 UTC
Labels: bug, Can't Reproduce

**Comment by gnunn1** [comment] 2017-01-22 15:45
I've checked in a fix for this, please test it out. Note that when switching between Wayland and X11 via logout/login I found that the Wayland environment variables would hang around on the X sessions causing terminix to think it was running under X. To avoid this, do a full restart when switching between the two. I'll open a new issue for Wayland detection.

**Comment by Jiehong** [comment] 2017-01-22 16:41
Just tried the last commit (9e67a75f03c9), and rebooted in Wayland directly:

```
getQuakePosition:1126 Wayland detected
getQuakePosition:1150 Monitor geometry: monitor=0, x=0, y=0, width=2880, height=1800
getQuakePosition:1157 Scaled monitor geometry: monitor=0, scaleFactor=2, x=0, y=0, width=1440, height=900
getQuakePosition:1194 Quake window: monitor=0, x=0, y=0, width=1440, height=252
moveAndSizeQuake:1115 Actually move/resize quake window
getQuakePosition:1126 Wayland detected
getQuakePosition:1150 Monitor geometry: monitor=0, x=0, y=0, width=2880, height=1800
getQuakePosition:1157 Scaled monitor geometry: monitor=0, scaleFactor=2, x=0, y=0, width=1440, height=900
getQuakePosition:1194 Quake window: monitor=0, x=0, y=0, width=1440, height=252
moveAndSizeQuake:1115 Actually move/resize quake window
```

(Interesting that it prints the same stuff twice in a row).

But the scaling of the window's height is working now!

Although, the window isn't positioned at the top of the screen, but in the center:

![capture](https://cloud.githubusercontent.com/assets/1061229/22183981/f9473f7e-e0c9-11e6-9b4e-85093e594281.png)

Should I opened a new issue for the window's position?

**Comment by bil-elmoussaoui** [comment] 2017-01-22 17:57
@Jiehong the applications can't move themselves to a specific position on Wayland !

**Comment by gnunn1** [comment] 2017-01-22 18:01
Unfortunately there's no point in opening an issue for it, as @bil-elmoussaoui notes an app cannot control its position under Wayland. The things i'm doing usually work out but I can't guarantee that it will always work.

**Comment by Jiehong** [comment] 2017-01-22 18:04
Alright. Thanks for all the time you put in this. I dare to say it was pleasant to open a ticket here 😄

**Comment by gnunn1** [comment] 2017-01-22 18:11
Btw, see #494 for more info on this issue.
