### ISSUE TITLE
Wrong font color in context popover with Ambiance theme in Ubuntu

### ISSUE THREAD

**Issue by valmar** [gnunn1/terminix#275] opened 2016-04-23 16:50 UTC
Dear gnunn1, first of all thank you for this fabulous terminal emulator.

I would like to report that in Ubuntu 16.04, using the default Ambiance theme, the font color in the context popover is wrong and the text is very hard to read. I attach a cropped screenshot.

Thank you for looking into this

![screenshot from 2016-04-23 18-40-23](https://cloud.githubusercontent.com/assets/558469/14762780/2743302c-0984-11e6-9ebb-c6db2c43c373.png)

**Comment by gnunn1** [comment] 2016-04-23 19:02
I'll have a look but I suspect this is a bug in Ambiance and not Terminix

**Comment by stuaxo** [comment] 2016-04-25 10:15
I have the same bug using Flatabulous Gtk theme in Ubuntu. 

The dropdown colours don't seem correct as well:

![similar bug?](http://imgur.com/jGauEh7.png)

Menus in Nautilus, Gnome Terminal look OK, as does the right-click window menu.   Will keep using this as you've made something too useful :)

Not quite sure how to debug this, and suspect the themes themselves more (+Gtk changes around CSS theming).

**Comment by stuaxo** [comment] 2016-04-25 10:16
Ah, confirmed the same bug in Gedit, so it is the theme - ignore this.

**Comment by valmar** [comment] 2016-04-25 10:27
Indeed, you made something too useful!

I have to say that the menu that @stuaxo has shown in the picture looks fine with ambiance. It is only the right-click popover giving trouble

**Comment by gnunn1** [comment] 2016-04-25 14:58
This is a bug in Ubuntu IMHO, see #217 for another one that I fixed. Fixing the color is trickier though because a simple override in the terminix CSS will affect all themes which I'm not willing to do. I tried setting it to the named theme color, insensitive_fg_color, but doesn't look like Ambiance supports that correctly as well.

I really think I'm going to need an Ubuntu Ambiance specific CSS file to address this and some of the other issues, more research needed.

**Comment by stuaxo** [comment] 2016-04-25 15:54
It's worth opening a launchpad bug ... I don't expect that to make them fix it, but at least if you work out a fix, they might take it.

**Comment by valmar** [comment] 2016-04-25 16:10
I would like to report it as a general popover bug as opposed to a terminix
bug, but I cannot find another app that uses popovers in Ubuntu to test if
I can reproduce the bug. Anyone has any idea?

Valerio

**Comment by stuaxo** [comment] 2016-04-25 16:55
It looks like gedit, does, but I can't seem to repro the bug in it.   Will have a try with GtkParasite later.

**Comment by stuaxo** [comment] 2016-04-25 16:56
A lot of the programmes listed in here are popover enabled in Ubuntu (a few not, like Nautilus).
https://blogs.gnome.org/mclasen/2014/03/18/new-in-gtk-3-12-popovers/

**Comment by gnunn1** [comment] 2016-04-25 18:05
Builder would be a good one to test since I based my UI on that.

**Comment by gnunn1** [comment] 2016-04-26 21:01
As far as I can tell, Builder has the same issues.

![screenshot from 2016-04-26 15-00-02](https://cloud.githubusercontent.com/assets/9358238/14834083/ca8dde20-0bbf-11e6-9e92-c33875910a77.png)

**Comment by gnunn1** [comment] 2016-04-27 14:20
I've opened a launchpad issue for it here:

https://bugs.launchpad.net/ubuntu/+source/ubuntu-themes/+bug/1575701

I'm closing this and marking it as Won't Fix since in my opinion this is an issue with Ambiance. I debated about fixing it myself locally but after consideration it doesn't make sense for me to do it otherwise it puts me in the business of fixing every theme that has issues.

**Closed by gnunn1** 2016-04-27 14:20 UTC

**Comment by stuaxo** [comment] 2016-04-27 17:11
Definitely makes sense, I expect Ubuntu Aerobic Asp to have it fixed in 2019 ;)
