### ISSUE TITLE
Thumbnails are not updated on reattaching sessions

### ISSUE THREAD

**Issue by alex285** [gnunn1/terminix#87] opened 2016-02-20 12:34 UTC
Always reproduce as it seems on video
https://www.youtube.com/watch?v=gPArxtvCmY4

That happens on Gnome 320 beta.

**Comment by gnunn1** [comment] 2016-02-20 14:33
That's an interesting effect. I re-worked the creation of the drag image to use the same rendering code that the sidebar uses, maybe I broke something here. Did it do this on the previous version?

**Comment by alex285** [comment] 2016-02-20 14:48
No it wasn't doing it on the previous versions. I didnt check a few commits back to see when that happened. Cant do now. I do later!

**Comment by gnunn1** [comment] 2016-02-20 14:49
No worries, I'm pretty sure I know what code changed to cause this, just not sure why. It also looks specific to Gnome 3.20, can't reproduce on 3.18. I'll test it later today on Rawhide.

**Comment by alex285** [comment] 2016-02-20 16:26
I should open a different bug, but since you're gonna try Rawhide, I just add it here. Re-attaching a session to a new window, isnt working at all on Wayland session.

**Comment by gnunn1** [comment] 2016-02-20 18:14
I'm thinking the drag image being left behind is either a bug in 3.20 or something changed. When you detach a terminal and drop it outside you get a NO_TARGET on the dragFailed. If I can handle it, by detaching the terminal, I return true which indicates it was successfully handled. The image sticks when I return true but disappears when I return false, unfortunately it disappears with the un-handled animation (i.e moving the source of the drag) rather then just disappearing quietly. I need to look at the code for detaching tabs from GtkNotebook in 3.20 because my code was based on what was being done here in 3.18.

**Comment by gnunn1** [comment] 2016-02-21 00:50
mclasen indicated on IRC that there are issues with handling DND drops on the root window, he referenced bug 762104 (https://bugzilla.gnome.org/show_bug.cgi?id=762104) that are still being worked on. As for the Wayland DND, there are a number of bugs open with that as well so I think this point I'm going to defer this until things firm up.

I'm going to close this issue but reference it in the Gnome 3.19 catch-all.

**Closed by gnunn1** 2016-02-21 00:50 UTC
Labels: bug
