### ISSUE TITLE
Terminix stable version starts in root directory again - CentOS-7

### ISSUE THREAD

**Issue by ivoarch** [gnunn1/terminix#337] opened 2016-05-22 16:08 UTC
Today I installed the stable version 1.0.0 and for a big surprise when I launch Terminix, it starts in root directory :( . 

Version 0.60 works fine on EL7 .

Sorry that I have not done this test before releasing the version stable!

**Comment by gnunn1** [comment] 2016-05-22 20:38
You should be able to set DBusActivatable to false in the desktop file as a temporary workaround.

I need to do some thinking about whether keeping DBusActivatable is worth the overall aggravation it's causing at this point.

**Comment by ivoarch** [comment] 2016-05-22 22:25
Does not work!!

```
~] cat /usr/share/applications/com.gexperts.Terminix.desktop | grep -i DBus
DBusActivatable=false
```
And Terminix it starts in root directory again.

**Comment by gnunn1** [comment] 2016-05-22 23:42
Did you restart the desktop (Alt-F2, "r" in gnome-shell)?

**Comment by gnunn1** [comment] 2016-05-23 01:25
I just tried it here in Oracle Linux 7.2 and couldn't replicate. Are you using Gnome Shell as your desktop environment or something else?

**Comment by gnunn1** [comment] 2016-05-23 01:52
Never mind, I can reproduce after all, had a problem with my VM. Looks like the same issue as Unity, except now that I'm only applying the workaround to Unity it fails in this case. Unfortunately checking by desktop environment doesn't appear to be the answer.

**Comment by ivoarch** [comment] 2016-05-23 08:16
Confirmed with the change of DBusActivatable to false works!! My fault, I started terminix from old starter on my desktop . I tried from the menu and terminix starts in my $HOME directory .

I think it would be nice to be solved the problem in the stable version for el7, as something like this [patch](https://gist.github.com/ivoarch/0811d00eb89c94dff19695fc74b8547d)  .spec file then rebuild again .

**Comment by gnunn1** [comment] 2016-05-23 15:15
I've ccommitted my last attempt to address this, if it doesn't work out for everyone I'll drop the DBusActivatable from the desktop file.

**Comment by gnunn1** [comment] 2016-05-29 14:21
Fixed with last commit

**Closed by gnunn1** 2016-05-29 14:21 UTC
Labels: bug
